### ISSUE TITLE
Malware URL in wp-super-cache/wp-cache.php

### ISSUE THREAD

**Issue by WFSupport** [Automattic/wp-super-cache#106]
Google is flagging a url included on line 3333 of wp-super-cache/wp-cache.php which causes Wordfence to flag it as well.  The line is commented out so I believe removal would not cause an issue.  

			// http://bytes.com/topic/php/answers/3917-seconds-converted-hh-mm-ss

There is a post open in the wordpress forums about this that I answered. 
https://wordpress.org/support/topic/malware-url-included-in-wp-cachephp-via-wordfence-security-alert?replies=3#post-8117882

**Comment by kraftbj** [comment]
Thanks! Fixed in https://github.com/Automattic/wp-super-cache/commit/1d5523ac2c4da08140cbd746be3f5e1a66304c35 and released.

**Comment by WFSupport** [comment]
I appreciate it!  :)
