### ISSUE TITLE
Expiry Time & Garbage Collection changing back to Clock schedule instead of Timer when submitting

### ISSUE THREAD

**Issue by glennsantos** [Automattic/wp-super-cache#14]
The fix was actually already implemented by someone, very fast fix.

Hope Automattic fixes this quickly. Can be frustrating for regular WP Super Cache users.

Fix here: http://wordpress.org/support/topic/found-problem-with-advanced-tab-garbage-collection-settings?replies=1

**Comment by kraftbj** [comment]
Fixed via #49
