### ISSUE TITLE
Caching Custom Post Types and Custom Taxonomies pages

### ISSUE THREAD

**Issue by marcomarsala** [Automattic/wp-super-cache#146]
feature suggestion

**Comment by marcomarsala** [comment]
Seems working now after many reinstallations, but didn't always work

**Comment by Ontario7** [comment]
We have some customs post types, for example /segway-tours/
After opening url manually cache works perfect.
But in preload mode those pages does not added to cache index.
Waht can we do? Take a look [here](https://new.pragueonsegway.com/segway-tours/segway-fun-prag/)

**Comment by Ontario7** [comment]
One more question.
Seems that preloading works fine on basic pages. But for mobile versions does not work.
By the way thanks that mobile pages are saved in cache after user requests the page.

Seems like that it could be easier pre-load all the site pages by external bash script using sitemap and curl :)

**Comment by marcomarsala** [comment]
I confirm it won't preload mobile pages (obviously, if Mobile support is activated) or custom post types.

**Comment by Ontario7** [comment]
Is there the way to force it in the next version?
Just collect custom fields types. Or you can collect all the pages from /sitemep.xml  

One more bug:
On the dev.site.com version we have the plugin ON with caching OFF option. Just for turn it on after public next ver after update. Preload was turn on before caching off.

Once in several days we got email from dev that prelaod starts....

**Comment by Ontario7** [comment]
We solve this problem by the linux feature wget.

1. So turning off preload in super cache and turning off garbage collection.
2. Run the script below on cron like every 3 hours, preloading desktop also as mobile version.

DOMAIN='domain.com'
rm -R /home/admin/web/$DOMAIN/public_html/wp-content/cache/supercache/$DOMAIN/
# Fetching desktop version
wget --spider -o wget.log -e robots=off -r -l 5 -p -S --header="X-Bypass-Cache: 1" $DOMAIN --wait 1
# Fetching mobile version
wget --spider -o wget-mob.log -e robots=off -r -l 5 -p -S --header="X-Bypass-Cache: 1" $DOMAIN --wait 1 --user-agent='iOS 4_3 – iPhone – Safari 533.17.9'

**Comment by Ontario7** [comment]
Are there any news about this non-preload WPSuperCashe issue?
