### ISSUE TITLE
Preserve existing HTTP headers (Link, etc)

### ISSUE THREAD

**Issue by bfred-it** [Automattic/wp-super-cache#165]
The cached files don't send out the original headers like `Link`

Notice the difference between a fresh serve and a cached serve:

<img width="886" alt="screen shot 2017-01-18 at 10 29 51" src="https://cloud.githubusercontent.com/assets/1402241/22047234/a2a12efc-dcda-11e6-9e73-cc0a005bf5f3.png">

This happens with either mod_rewrite and PHP caching.

The Link headers are particularly useful with HTTP/2 push via [plugin](https://wordpress.org/plugins/http2-server-push/) + [CloudFlare](https://blog.cloudflare.com/announcing-support-for-http-2-server-push-2/) (neither shown in the screenshot)

**Comment by donnchawp** [comment]
Unfortunately this is a long standing issue. Did you try legacy caching? That stores the request headers too.

I have plans to improve how legacy caching works but it's probably a long way off right now.

**Comment by TUNER88** [comment]
@donnchawp Its very important to preserve existing headers, in some cases it can cause **security issues**!

E.g. if some security related headers are suddenly missing like:
```
X-Frame-Options: DENY
Referrer-Policy: no-referrer-when-downgrade
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Security-Policy: ...
```

**Comment by donnchawp** [comment]
Thanks for those links @TUNER88. Comet Cache has a much longer list of cache headers which I will copy and credit them. 

It doesn't include "Referrer-Policy" but I'll add that too.

**Comment by donnchawp** [comment]
In #287 I added a bunch of headers, and a filter to allow site owners to modify them.

I wonder still, if the plugin detects headers beyond the usual if it should drop back to standard caching so those headers are cached automatically? Things like content-type, length, encoding, last-modified, X-Pingback, etag, cache-control and pragma could be ignored as PHP can recreate most of them. It might be worth adding as an advanced option.

**Comment by donnchawp** [comment]
I also added a new setting that will cache all headers, but then it uses standard caching instead of supercaching but there's not much speed difference between them anyway so worth it if you need special headers.
