### ISSUE TITLE
Notice: 	Use of undefined constant IPC_CREAT - assumed 'IPC_CREAT'

### ISSUE THREAD

**Issue by rene-hermenau** [Automattic/wp-super-cache#166]
wp-content/plugins/wp-super-cache/wp-cache-phase2.php:175

**Comment by donnchawp** [comment]
That's odd. AFAICT that's a constant defined by the system so it should always be there. It's not defined by the plugin. Have you excluded any PHP modules from loading?

**Comment by rene-hermenau** [comment]
I suppose it's a php bug. It's happening on other systems as well: 
https://www.google.de/search?q=IPC_CREAT&q=php+ipc_creat+undefined+constant

My php version is  Version 5.4.39-0 on Debian 7.0 running with an older APC version.
I think it's time to upgrade:-) It likely will resolve it.

Thank you

**Comment by donnchawp** [comment]
Disable coarse file locking on the Advanced Settings page. It's disabled by default.

**Comment by rene-hermenau** [comment]
Thank you mate. That's working :1st_place_medal:  I obviously enabled this by accident
