### ISSUE TITLE
On post update: too much stuff is deleted, not requested by me or settings?

### ISSUE THREAD

**Issue by DrLightman** [Automattic/wp-super-cache#169]
Hello, using WP 4.6.2, WPSC 1.4.8

I'm debugging on localhost, keeping an eye on supercache directory and debug log.

What I see is, when I update a post, all other 2 test posts in the blog (**ajsdjasj** and **qweqwe**) and the front page that I have in cache in that moment, get deleted too. I don't want this. The 2 posts make no sense, the front page per setting is off.

My garbage collection is set to 0 because I wanted it turned off while testing.

These are my settings:

mod_rewrite caching.

[x] Compress pages so they’re served more quickly to visitors. (Recommended)
[ ] Don’t cache pages for known users. (Recommended)
[ ] Don’t cache pages with GET parameters. (?x=y at the end of a url)
[x] Make known users anonymous so they’re served supercached static files.
[ ] Cache rebuild. Serve a supercache file to anonymous users while a new file is being generated. (Recommended)
[ ] Proudly tell the world your server is Stephen Fry proof! (places a message in your blog’s footer)

[x] Mobile device support. (External plugin or theme required. See the FAQ for further details.)

[ ] Remove UTF8/blog charset support from .htaccess file. Only necessary if you see odd characters or punctuation looks incorrect. Requires rewrite rules update.
[ ] Clear all cache files when a post or page is published or updated.
[ ] Extra homepage checks. (Very occasionally stops homepage caching) (Recommended)
[x] Only refresh current page when comments made.
[ ] List the newest cached pages on this page.
[ ] Coarse file locking. You probably don’t need this but it may help if your server is underpowered. Warning! May cause your server to lock up in very rare cases!
[ ] Late init. Display cached files after WordPress has loaded. Most useful in legacy mode.

$wp_cache_clear_on_post_edit = 0; //Added by WP-Cache Manager
in /wp-content/wp-cache-config.php

First 7 lines are ok. Then there are the **bolded** one that are the log lines that do the **extra unwanted pruning**, not requested by me. I'm going to edit post 1890 ( /video-singolo/ ) and I want only that cache to be pruned.

/wp-admin/post.php wp_cache_post_edit: Clearing cache for post 1890 on post edit.
/wp-admin/post.php supercache dir: D:\Siti\wptest\wp-content/cache/supercache/www.wptest.local/video-singolo/
/wp-admin/post.php wp_cache_post_id_gc post_id: 1890 http://www.wptest.local/video-singolo/ clearing cache in D:\Siti\wptest\wp-content/cache/supercache/www.wptest.local/video-singolo/.
/wp-admin/post.php prune_super_cache: wp_cache_rebuild_or_delete( D:\Siti\wptest\wp-content/cache/supercache/www.wptest.local/video-singolo/index.html )
/wp-admin/post.php rebuild_or_gc: deleted D:\Siti\wptest\wp-content/cache/supercache/www.wptest.local/video-singolo/index.html
/wp-admin/post.php prune_super_cache: wp_cache_rebuild_or_delete( D:\Siti\wptest\wp-content/cache/supercache/www.wptest.local/video-singolo/index.html.gz )
/wp-admin/post.php rebuild_or_gc: deleted D:\Siti\wptest\wp-content/cache/supercache/www.wptest.local/video-singolo/index.html.gz
**/wp-admin/post.php wp_cache_post_id_gc clearing cache in D:\Siti\wptest\wp-content/cache/supercache/www.wptest.local/video-singolo//page/.
/wp-admin/post.php prune_super_cache: exiting as file/dir does not exist: D:\Siti\wptest\wp-content/cache/supercache/www.wptest.local/video-singolo//page/
/wp-admin/post.php wp_cache_post_id_gc clearing cache in D:\Siti\wptest\wp-content/cache/supercache/www.wptest.local//page/.
/wp-admin/post.php prune_super_cache: exiting as file/dir does not exist: D:\Siti\wptest\wp-content/cache/supercache/www.wptest.local//page/
/wp-admin/post.php Post change: supercache enabled: deleting cache files in D:\Siti\wptest\wp-content/cache/supercache/www.wptest.local/
/wp-admin/post.php Post change: deleting page_on_front and page_for_posts pages.
/wp-admin/post.php Post change: page_on_front 1383
/wp-admin/post.php supercache dir: D:\Siti\wptest\wp-content/cache/supercache/www.wptest.local/
/wp-admin/post.php wp_cache_post_id_gc post_id: 1383 http://www.wptest.local/ clearing cache in D:\Siti\wptest\wp-content/cache/supercache/www.wptest.local/.
/wp-admin/post.php wp_cache_post_id_gc clearing cached index files in D:\Siti\wptest\wp-content/cache/supercache/www.wptest.local/.
/wp-admin/post.php prune_super_cache: wp_cache_rebuild_or_delete( D:\Siti\wptest\wp-content/cache/supercache/www.wptest.local/ajsdjasj/index.html )
/wp-admin/post.php rebuild_or_gc: deleted D:\Siti\wptest\wp-content/cache/supercache/www.wptest.local/ajsdjasj/index.html
/wp-admin/post.php prune_super_cache: wp_cache_rebuild_or_delete( D:\Siti\wptest\wp-content/cache/supercache/www.wptest.local/ajsdjasj/index.html.gz )
/wp-admin/post.php rebuild_or_gc: deleted D:\Siti\wptest\wp-content/cache/supercache/www.wptest.local/ajsdjasj/index.html.gz
/wp-admin/post.php prune_super_cache: wp_cache_rebuild_or_delete( D:\Siti\wptest\wp-content/cache/supercache/www.wptest.local/qweqwe/index.html )
/wp-admin/post.php rebuild_or_gc: deleted D:\Siti\wptest\wp-content/cache/supercache/www.wptest.local/qweqwe/index.html
/wp-admin/post.php prune_super_cache: wp_cache_rebuild_or_delete( D:\Siti\wptest\wp-content/cache/supercache/www.wptest.local/qweqwe/index.html.gz )
/wp-admin/post.php rebuild_or_gc: deleted D:\Siti\wptest\wp-content/cache/supercache/www.wptest.local/qweqwe/index.html.gz
/wp-admin/post.php wp_cache_post_id_gc clearing cache in D:\Siti\wptest\wp-content/cache/supercache/www.wptest.local//page/.
/wp-admin/post.php prune_super_cache: exiting as file/dir does not exist: D:\Siti\wptest\wp-content/cache/supercache/www.wptest.local//page/
/wp-admin/post.php wp_cache_post_id_gc clearing cache in D:\Siti\wptest\wp-content/cache/supercache/www.wptest.local//page/.
/wp-admin/post.php prune_super_cache: exiting as file/dir does not exist: D:\Siti\wptest\wp-content/cache/supercache/www.wptest.local//page/**

Any idea why this is happening?

Thank you

**Comment by Sophist-UK** [comment]
See #98.

**Comment by DrLightman** [comment]
So it seems the issue is still ongoing?

**Comment by Sophist-UK** [comment]
Handling it properly by being intelligent about what cached pages need to be invalidated for all the different actions that can happen (change in permalink, unpublish, change of category, change of tag, etc. etc.) needs careful coding.

Despite this plugin being stated as owned by Automattic (the authors of Wordpress) as far as I can tell it was written by, and is supported by, an individual employee in his spare time as and when he has an interest. (So saying it is written and therefore supported by Automattic is perhaps a bit disingenuous. You would have thought that considering this, and bearing in mind the number of installations and the impact on their reputation Automattic would be interested in supporting this plugin properly - but apparently not.)

**Comment by DrLightman** [comment]
Well since it's a free plugin, I don't want to be harsh on that. It's still helping me even in its actual not perfect condition.

I'll try to look into it myself when I have some spare time and publish the results if I'll find something.

**Comment by Sophist-UK** [comment]
Since it is published here on Github there is nothing to stop anyone from developing code improvements and submitting them for consideration. And clearly someone is monitoring this because some PRs were merged as recently as last month.

So if you develop a full blown cache invalidation scheme - or even an improvement on the current one - people will be very pleased, particularly with those with a large but infrequently changed web site who cannot afford to have their cache cleared excessively.

**Comment by DrLightman** [comment]
Okay I think I nailed it, I need confirmations from you, but the tests are promising, it seems to work. Updating a post, deletes the only post's cache based on the user preference in settings and leave the rest untouched. It's a small mod, I don't know if it covers all possibile cases, but I think I'll make it into production on my site because in localhost it works for my needs.

The modifications are to be made in the file `\wp-super-cache\wp-cache-phase2.php`

Look for the `function wp_cache_post_change( $post_id )` declaration, I have around line 1142 but I don't know if it's your case since I added comments here and there while debugging.

**First**, add the global variable `$wp_cache_clear_on_post_edit` to globals already defined just below there.

Before:

```php
global $file_prefix, $cache_path, $blog_id, $super_cache_enabled, $blog_cache_dir, $blogcacheid, $wp_cache_refresh_single_only, $wp_cache_object_cache;
```

After:

```php
global $file_prefix, $cache_path, $blog_id, $super_cache_enabled, $blog_cache_dir, $blogcacheid, $wp_cache_refresh_single_only, $wp_cache_object_cache, $wp_cache_clear_on_post_edit /* <- New by DrLightman - avoid prune all cache when updating a post */;
```

**Second**, go down about 30 lines where it says:

```php
	} else {
		$all = true;
	}
```

And change it all in:

```php
	/* New by DrLightman - start */
	} elseif( isset( $wp_cache_clear_on_post_edit ) && $wp_cache_clear_on_post_edit ) {
		$all = true;
	} else {
		$all = false;
	}
	/* New by DrLightman - end */
```

Watch out in the last `else`, before was `$all = true`, now it's `$all = false`. Better copy/paste all the block.
And that should be it. Do your tests and let me know if it works for you too.

**Comment by DrLightman** [comment]
New correct debug log after applying the fix above:

/wp-admin/post.php wp_cache_post_edit: Clearing cache for post 1890 on post edit.
/wp-admin/post.php supercache dir: D:\Siti\wptest\wp-content/cache/supercache/www.wptest.local/video-singolo/
/wp-admin/post.php wp_cache_post_id_gc post_id: 1890 http://www.wptest.local/video-singolo/ clearing cache in D:\Siti\wptest\wp-content/cache/supercache/www.wptest.local/video-singolo/.
/wp-admin/post.php prune_super_cache: wp_cache_rebuild_or_delete( D:\Siti\wptest\wp-content/cache/supercache/www.wptest.local/video-singolo/index.html )
/wp-admin/post.php rebuild_or_gc: deleted D:\Siti\wptest\wp-content/cache/supercache/www.wptest.local/video-singolo/index.html
/wp-admin/post.php prune_super_cache: wp_cache_rebuild_or_delete( D:\Siti\wptest\wp-content/cache/supercache/www.wptest.local/video-singolo/index.html.gz )
/wp-admin/post.php rebuild_or_gc: deleted D:\Siti\wptest\wp-content/cache/supercache/www.wptest.local/video-singolo/index.html.gz
/wp-admin/post.php wp_cache_post_id_gc clearing cache in D:\Siti\wptest\wp-content/cache/supercache/www.wptest.local/video-singolo//page/.
/wp-admin/post.php prune_super_cache: exiting as file/dir does not exist: D:\Siti\wptest\wp-content/cache/supercache/www.wptest.local/video-singolo//page/
/wp-admin/post.php wp_cache_post_id_gc clearing cache in D:\Siti\wptest\wp-content/cache/supercache/www.wptest.local//page/.
/wp-admin/post.php prune_super_cache: exiting as file/dir does not exist: D:\Siti\wptest\wp-content/cache/supercache/www.wptest.local//page/
**/wp-admin/post.php wp_cache_post_change: not deleting all pages.
/wp-admin/post.php wp_cache_post_change: not deleting front static page.**
/wp-admin/post.php wp_cache_post_change: checking D:\Siti\wptest\wp-content/cache/meta/
/wp-admin/post.php wp_cache_post_edit: Already processed post 1890.
/wp-admin/post.php wp_cache_post_change: Already processed post 1890.

**Comment by Sophist-UK** [comment]
Please submit this as a PR.

**Comment by DrLightman** [comment]
Okay I'll see if I'm able to do it.

But now I'm just noticing in the last log I posted, these 2 lines shouldn't be there, since they are trying to delete paginated pages of the home page (next/prev links), but per my settings it's not requested:

/wp-admin/post.php wp_cache_post_id_gc clearing cache in D:\Siti\wptest\wp-content/cache/supercache/www.wptest.local//page/.
/wp-admin/post.php prune_super_cache: exiting as file/dir does not exist: D:\Siti\wptest\wp-content/cache/supercache/www.wptest.local//page/

**Comment by DrLightman** [comment]
I hope I did it right, I wasn't familiar with the PR mechanism until yesterday.

**Comment by Sophist-UK** [comment]
No - you have created a branch in your own fork (i.e. copy) of the code base.

You now need to submit a PR (Pull Request) to the main code base here so that someone can review it and merge it into the main code base.

But your branch appears at first sight to match the code changes you proposed above.

**Comment by Sophist-UK** [comment]
Well done!!

**Comment by DrLightman** [comment]
Thanks to you for the PR submit idea ;)

Now let's hope it will helps to fix this issue. If not my exact code at least I think I narrowed down the area of interest in the code.

**Comment by donnchawp** [comment]
Thanks @DrLightman for the patch and the excellent ticket. The debug log showed me that you have a static front page and that led me to the right piece of code.

The plugin is meant to delete the front page cache, the posts page, and any /page/ archives because if you've edited a post you'll want the front page to update in case there's a widget showing that post, or in the case of the posts page it may show the contents of the post you just edited. It shouldn't of course have removed the cache files for the other posts.

In wp-cache-phase2.php comment out the following line:
`wp_cache_post_id_gc( $siteurl, get_option( 'page_on_front' ), 'single' );`

That should stop the plugin deleting every cached file while deleting the other "archive" pages that need to be updated.

**Comment by donnchawp** [comment]
If you want the plugin to only delete the cache files for the current post being edited then that's a whole different issue.

**Comment by DrLightman** [comment]
Hello @donnchawp , I'm glad I have been of help.

So, If I got it right, to fix this #169 issue I should cancel my suggested changes and apply your one-lined modification/commentation?

**Comment by donnchawp** [comment]
Yeah, try that, but the plugin will delete more than just the page itself as I said above. I hope it works so we can close this ticket and the others.

**Comment by DrLightman** [comment]
Ok I'll repeat the same tests with these mods soon and I going to post the results.

**Comment by DrLightman** [comment]
Okay after removing my mod and applying yours, the logs looks almost the same to my fixed, so I think it's a good one!

/wp-admin/post.php wp_cache_get_cookies_values: /^wp-postpass|^comment_author_|^wordpress_logged_in_c0c9ee7e05ff87f0725b44c14dc3f60d/ Cookie detected: wordpress_logged_in_c0c9ee7e05ff87f0725b44c14dc3f60d
/wp-admin/post.php wp_cache_get_cookies_values: return: 2cb1c8b2dd506fe9d2cc56bf84c28427
/wp-admin/post.php In WP Cache Phase 2
/wp-admin/post.php Setting up WordPress actions
/wp-admin/post.php Not caching wp-admin requests.
/wp-admin/post.php wp_cache_post_edit: Clearing cache for post 1890 on post edit.
/wp-admin/post.php supercache dir: D:\Siti\wptest\wp-content/cache/supercache/www.wptest.local/video-singolo/
/wp-admin/post.php wp_cache_post_id_gc post_id: 1890 http://www.wptest.local/video-singolo/ clearing cache in D:\Siti\wptest\wp-content/cache/supercache/www.wptest.local/video-singolo/.
/wp-admin/post.php prune_super_cache: wp_cache_rebuild_or_delete( D:\Siti\wptest\wp-content/cache/supercache/www.wptest.local/video-singolo/index.html )
/wp-admin/post.php rebuild_or_gc: deleted D:\Siti\wptest\wp-content/cache/supercache/www.wptest.local/video-singolo/index.html
/wp-admin/post.php prune_super_cache: wp_cache_rebuild_or_delete( D:\Siti\wptest\wp-content/cache/supercache/www.wptest.local/video-singolo/index.html.gz )
/wp-admin/post.php rebuild_or_gc: deleted D:\Siti\wptest\wp-content/cache/supercache/www.wptest.local/video-singolo/index.html.gz
/wp-admin/post.php wp_cache_post_id_gc clearing cache in D:\Siti\wptest\wp-content/cache/supercache/www.wptest.local/video-singolo//page/.
/wp-admin/post.php prune_super_cache: exiting as file/dir does not exist: D:\Siti\wptest\wp-content/cache/supercache/www.wptest.local/video-singolo//page/
/wp-admin/post.php wp_cache_post_id_gc clearing cache in D:\Siti\wptest\wp-content/cache/supercache/www.wptest.local//page/.
/wp-admin/post.php prune_super_cache: exiting as file/dir does not exist: D:\Siti\wptest\wp-content/cache/supercache/www.wptest.local//page/
/wp-admin/post.php Post change: supercache enabled: deleting cache files in D:\Siti\wptest\wp-content/cache/supercache/www.wptest.local/
**/wp-admin/post.php Post change: deleting page_on_front and page_for_posts pages.**
/wp-admin/post.php Post change: page_on_front 1383
/wp-admin/post.php wp_cache_post_change: checking D:\Siti\wptest\wp-content/cache/meta/
/wp-admin/post.php wp_cache_post_edit: Already processed post 1890.
/wp-admin/post.php wp_cache_post_change: Already processed post 1890.

Very good:
the cache of other blog's posts is not pruned!

Not so good:
the bold line is an unwanted action, per my specific settings.
I understand that the edited post could appear in some front page widget/s, but in certain site setups, one admin could choose to leave the cached version, for better performance. Let's say one big news site has many authors writing/updating posts (my case), it would be preferable not to delete the cache in response of these random minion's actions and follow the admin setup to let say delete the front page cache at a static interval of 5 or 10 minutes. In my particular setup I disabled WP gc and made a separate cron script to do the gc.

My WPSC settings that may be somehow related to a front page pruning are:

[ ] Clear all cache files when a post or page is published or updated.
[ ]  Extra homepage checks. (_not even sure if this is related to the situation above_)
[x]  Only refresh current page when comments made.

Maybe settings for the front page should be added to be more clear on what may happen when one publish/updates/deletes a post, because based on the settings above, it's not evident why the front page should get pruned after updating a post.

Thank you again for having the time to check on this issue ;)

**Comment by donnchawp** [comment]
Great! I'm glad that worked!

I think we'll need a new section in the settings page called "When a post is updated" where the site owner can decide what pages are deleted when a page is updated or comment made.

As a first pass, I'll add a filter to the post_change function that will allow you to modify the value of $all - if it's 0 the "page on front" checks won't be done and those files won't be deleted. You can add the hook on that filter in your theme functions.php or an mu plugin.

**Comment by donnchawp** [comment]
I added a filter called "wpsc_delete_related_pages_on_edit" on $all. If that filter returns 0 then only the current page will be deleted. The only changes have been to wp-cache-phase2.php so grab that file from [here](https://github.com/Automattic/wp-super-cache/blob/eadec4e310e56ae6e190b0aa233dad3d8b24e0fa/wp-cache-phase2.php) and overwrite the one on your test server to test it.

**Comment by talgalili** [comment]
@donnchawp it might also help to have another button so instead of just "clear cache" or "clear stale cache" to have "clear home page", "clear pagniated pages" (not including search pages!), "clear search pages" etc.

**Comment by talgalili** [comment]
Hi @donnchawp 

Would using this do the trick?

function return0( ) {
  // Process content here
  return 0;
}
add_filter( 'wpsc_delete_related_pages_on_edit', 'return0');
