### ISSUE TITLE
design flaw causing problems with preload when using self-signed certificate or service like CloudFlare and Incapsula

### ISSUE THREAD

**Issue by vstoykovbg** [Automattic/wp-super-cache#170]
Preload is working by WP Super Cache sending requests to the web server using WP's [http](https://codex.wordpress.org/HTTP_API) API.

What could go wrong?

1) Cloudflare/Incapsula blocking some or all requests made by WordPress.
_Solution: add your domain name to `/etc/hosts` with your local IP address._
2) When using self-signed SSL certificate requests will not be triggering PHP (cache will not be created or updated).
_Solution: use valid certificate or add your certificate to `wp-includes/certificates/ca-bundle.crt` (see below for details)._
3) CloudFlare/Incapsula will serve old cached content, so the PHP will not get triggered and cache will not be updated.
_Solution: same as `1`._
4) When using NginX (configured this way) requests are served without touching PHP. If there are old cache files they will not be updated when garbage collection is turned off (`[x]  Preload mode (garbage collection only on legacy cache files. Recommended.)`).
_Solution: make exemption in `nginx.conf` based on user agent (see below)._

Also I suggest to disable WP-CRON: Add `define('DISABLE_WP_CRON', true);` to wp-config.php and add a cron job to be executed every minute with the correct username: ```cd /home/UserAccountChangeMe/public_html/ ; php -q wp-cron.php`;```.

**Comment by talgalili** [comment]
Is this always happening? if so then this is a big issue.

**Comment by vstoykovbg** [comment]
I don't know how often service providers like CloudFlare and Incapsula are blocking request from user agents "WordPress ...". 

Also this is very inefficient - to send request to another server, etc.  This can be solved by adding the domain name to /etc/hosts with the local IP address. This way no CloudFlare/Incapsula will be involved. However, this makes another problem - if certificate is expired or self-signed it still won't work.

I made a workaround for 4th problem:
`
set $TestingThisFix 'Not our WordPress';

# Request from WordPress should always go to PHP
if ($http_user_agent ~* ^WordPress.*\ replaceme\.tld$ ) {
#if ($http_user_agent ~* WordPress ) {
	set $cache_uri 'null cache';
    set $TestingThisFix 'Our WordPress';
}

add_header Testing-This-Fix $TestingThisFix;
`

Don't forget to replace `replaceme\.tld` with your domain (and to escape the dot). Or just remove the line and uncomment the next. But there will be a possible problem - RSS feeds will not be cached when another blog is requesting them.

**Comment by vstoykovbg** [comment]
To fix issues with certificates somewhere should be inserted something like ` array( 'sslverify' => false )`, I am still searching where to add it.

Also, where are the SSL-related files, where I can add my own Certificate Authority?

**Comment by donnchawp** [comment]
It's not really a flaw in the plugin though, is it? They're problems with your server configuration.

- You're using a self signed cert when you should probably use Let's Encrypt.
- Your using Cloudflare which is meant to handle requests from your server. There's no way the plugin could preload those pages if WordPress is trying to send requests to a remote server rather than the localhost.

I think you should use a Let's Encrypt cert, and either stop using Cloudflare, or stop using WP Super Cache. You're making problems for yourself!

**Comment by vstoykovbg** [comment]
There are many users out there that use CloudFlare/Incapsula with WordPress.

The plugin could preload pages if WordPress is sending requests to a CloudFlare instead of localhost most of the time. But I suspect that CloudFlare may block some of these requests (and routing these requests via CloudFlare is not efficient). So, I am suggesting to add a warning in documentation that web server administrator should add the website to the /etc/hosts (with the local IP address) in order requests from WordPress to go directly to the web server (instead of going to the CloudFlare).

Also, I found out that there are many guides to configure Nginx with WordPress and WP Super Cahce that are wrong - they don't include exception for the "WordPress ... domain.tld" user agent.

**Comment by talgalili** [comment]
I am using cloudflare, and I'm not sure if I understand from this discussion what I should practically do. A more detailed step-by-step explanation would be helpful (or even a test if the preload is working).

**Comment by donnchawp** [comment]
@vstoykovbg - you're right that many sites use that combination but it's beyond the ability of most website owners to edit /etc/hosts because they're using a cheap hosting package and don't have root access. I'll see about adding a note to the readme.txt about Cloudflare though.

@talgalili - don't worry about it at all. Just use the plugin and don't bother using preload.

**Comment by talgalili** [comment]
@donnchawp But I love preload :)

I'd be happy to know if there are instructions on how to make it work.

**Comment by talgalili** [comment]
(I'm using a VPS)

**Comment by vstoykovbg** [comment]
I wrote example config file and added some instructions [here](https://github.com/vstoykovbg/nginx.conf-examples/blob/master/wp-super-cache-nginx.conf.md).
