### ISSUE TITLE
hardcoded 1&1 workaround in wp-cache.php breaks rewrite rules for other setups

### ISSUE THREAD

**Issue by iamwebrocker** [Automattic/wp-super-cache#19]
Hi,

in wp-cache.php (line 2779ff) there's a work around for a problem with german provider "1&1"s server config:

	$content_dir_root = $document_root;
	if ( strpos( $document_root, '/kunden/' ) === 0 ) {
		// http://wordpress.org/support/topic/plugin-wp-super-cache-how-to-get-mod_rewrite-working-on-1and1-shared-hosting?replies=1
		// On 1and1, PHP's directory structure starts with '/homepages'. The
		// Apache directory structure has an extra '/kunden' before it.
		// Also 1and1 does not support the %{DOCUMENT_ROOT} variable in
		// .htaccess files.
		// This prevents the $inst_root from being calculated correctly and
		// means that the $apache_root is wrong.
		//
		// e.g. This is an example of how Apache and PHP see the directory
		// structure on	1and1:
		// Apache: /kunden/homepages/xx/dxxxxxxxx/htdocs/site1/index.html
		// PHP:           /homepages/xx/dxxxxxxxx/htdocs/site1/index.html
		// Here we fix up the paths to make mode_rewrite work on 1and1 shared hosting.
		$content_dir_root = substr( $content_dir_root, 7 );
		$apache_root = $document_root;
	}

If was wondering what was going on with my installation and why WPSC had an additional (and wrong) "kunden" added to the rewrite cond. As it turns out, the above breaks on my setup, b/c the server document root path on germans "domainfactory" hosting also starts with "/kunden/...", but has none of the weird 1&1 thing - so here the path is fine by itself, but now the work around above produces a wrong path:

realpath:
  /kunden/XXXXXX/webseiten/mydomain/htdocs/blog/wp-content/....

rewritecond:
  /kunden/XXXXXX/webseiten/mydomain/htdocs/kunden/blog/wp-content/cache/supercache/%{SERVER_NAME}/$1/index.html.gz -f

as you can see, there is a second "kunden" inserted before the '/blog/....' part, which is the location of my wp install. After I commented out the complete if condition, the rewrite cond is correct.

Maybe the above work around could be made optional, perhaps via the settings, for those on 1&1 hosting? Assuming that a path starting with "/kunden/" equals 1&1 hosting with it's oddities is a bit optimistic. :-)

**Comment by iamwebrocker** [comment]
As a quick fix, make the if condition more "1and1" specific by adding "homepages/" to it. That's still dirty, but slightly more focussed to the 1&1 problem:
https://github.com/iamwebrocker/wp-super-cache/commit/5b4e789ae618018b69bba4cfc41a6a9359618a84

**Comment by iamwebrocker** [comment]
... any info/progress on that? Only a tiny fraction of users will be affected, I know, but for them this may be rather annoying.

**Comment by kraftbj** [comment]
Apologies for the delay. The adjustments sound reasonable to me.

**Comment by iamwebrocker** [comment]
No need to apologize, and thanks for the consideration. :+1:
