### ISSUE TITLE
Why PageSpeed Insights does not see compression?

### ISSUE THREAD

**Issue by cawa-93** [Automattic/wp-super-cache#210]
On my site (example.com) is a plugin WP Super Cache version 1.4.9
If you open the site in the browser, you can see that most of the files are downloaded from the cache. I also used the [checkgzipcompression.com](https://checkgzipcompression.com) service to check for the compression:
* example.com - It's GZIP Enabled.
* example.com/wp-content/themes/theme/style.css - GZIP is not enabled :(

As you can see, static files are not compressed

**Comment by lukecav** [comment]
@cawa-93 

Seems like mod_deflate is defined here in the Gzip rules.
/wp-cache.php#L3119

For Gzip compression on CSS files.

**AddOutputFilterByType DEFLATE text/css**
https://varvy.com/pagespeed/enable-compression.html
