### ISSUE TITLE
remove translations files

### ISSUE THREAD

**Issue by camaran** [Automattic/wp-super-cache#223]
remove translations file form zip and use wordpress translator system

**Comment by donnchawp** [comment]
This is something we should consider for the next release but it requires WordPress 4.6.

https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#loading-text-domain

**Comment by donnchawp** [comment]
There's no need to remove the translation files just yet. If updated translations are found they'll be used, but the translation has to be over 93% complete AFAIR. See the status of current translations here: https://translate.wordpress.org/projects/wp-plugins/wp-super-cache
