### ISSUE TITLE
Error when $cache_acceptable_files is NULL in wp_cache_ob_callback

### ISSUE THREAD

**Issue by Yunheng** [Automattic/wp-super-cache#226]
In the wp_cache_ob_callback($buffer) function, under some circumstances, it is possible for $cache_acceptable_files to be NULL. It does not fail when using a Desktop browser, however, when using a Mobile Browser it does.

This will cause the in_array function to fail as a NULL is being passed in.

**Comment by stodorovic** [comment]
This issue is most likely fixed by https://github.com/Automattic/wp-super-cache/commit/a44181b9a632402349fd505f65708d03d2a15f5c.
