### ISSUE TITLE
Stolen code in tiny cache

### ISSUE THREAD

**Issue by szepeviktor** [Automattic/wp-super-cache#234]
Hello!
I am developing a very tiny cache plugin that caches only `the_content()` calls thus the post content.

I've copied some of the deleting logic from wp-super-cache
https://github.com/szepeviktor/wordpress-plugin-construction/blob/master/tiny-cache.php#L70

**Comment by donnchawp** [comment]
You're very welcome to take as much code as you like!

**Comment by szepeviktor** [comment]
Thank you.
