### ISSUE TITLE
PHP Notice

### ISSUE THREAD

**Issue by Ishodnikov** [Automattic/wp-super-cache#236]
PHP Notice:  Undefined variable: supercache_home in /wp-content/plugins/wp-super-cache/wp-cache-phase2.php on line 1143

**Comment by dragonzap** [comment]
Change the 1143 and 1144 lines in wp-cache-pashe2.php  file.

Original:
```
wp_cache_debug( "wp_cache_post_id_gc clearing cache in {$supercache_home}page/." );
$supercache_home = get_supercache_dir();
```
Fixed:
```
$supercache_home = get_supercache_dir();
wp_cache_debug( "wp_cache_post_id_gc clearing cache in {$supercache_home}page/." );
```

**Comment by donnchawp** [comment]
Thanks @dragonzap - this was fixed back in https://github.com/Automattic/wp-super-cache/commit/db3959ffea7a746f2aee104e8ba90acc68e50d40 but I forgot to close this issue.
