### ISSUE TITLE
Sitemap broken

### ISSUE THREAD

**Issue by amitmalewar** [Automattic/wp-super-cache#237]
After activating WP Super cache there's an issue with a sitemap.

**Comment by talgalili** [comment]
Maybe you should say what is the issue, which plugin you are using for sitemap - or any other information that would help the developer to know your situation.

**Comment by amitmalewar** [comment]
I am using Yoast SEO plugin for the sitemap. But I have also tried jetpack sitemap, still same issue.

As a temporary fix, I have added following to the **Add here strings (not a filename) that forces a page not to be cached** in **ADVANCED setting section**.

```
sitemap(_index)?\.xml(\.gz)?
([a-z0-9_\-]+)?sitemap\.xsl
[a-z0-9_\-]+-sitemap([0-9]+)?\.xml(\.gz)?
```

**Comment by donnchawp** [comment]
Can you try master? A large number of changes have been made to how caching works and the sitemap is almost working correctly. It doesn't return the right content type, and despite caching the request it doesn't use the cache files. Still looking. :)

**Comment by amitmalewar** [comment]
I have tried master, improvement in speed but it doesn't fix the sitemap issue.

**Comment by donnchawp** [comment]
I think I may need to exclude sitemaps from caching. At least with Jetpack, the plugin can't capture the content-type so it has to default to text/html. If a sitemap plugin sets `$wp_query->is_feed` to true (the Google Sitemap Generator appears to do so) then it can probably be cached but I haven't tested that yet. is_feed() should return true for that. The recently added sitemap header code added to wp_cache_shutdown_callback() should be able to set the header correctly then.
The plugin tests is_feed() earlier in the caching process and would cache feeds as wpcache files, including content type too.
But it's up to the plugin author to make sure is_feed is set correctly.

**Comment by donnchawp** [comment]
Ah ha. A small mod to the Jetpack plugin fixes the issue for that. By editing and looking for serve_raw_and_die() I add this before the die():
```global $wp_query;
$wp_query->is_feed = true;
set_query_var( 'feed', 'sitemap' );```

Now the sitemap is cached and then served with the correct Content-Type. :)

**Comment by donnchawp** [comment]
Jetpack has been fixed with the addition of [this code](https://github.com/Automattic/jetpack/pull/7397). Other plugins will have to be updated so they identify sitemaps in some way, preferably in the same as above.
