### ISSUE TITLE
strpos(): Empty delimiter in /wp-content/plugins/wp-super-cache/wp-cache-phase1.php on line 576

### ISSUE THREAD

**Issue by marcomarsala** [Automattic/wp-super-cache#243]
The warning above fills server logs. Maybe an empty variable is used as delimiter parameter to `strpos` call?

**Comment by donnchawp** [comment]
It looks like $WPSC_HTTP_HOST is either not set or more likely is "" which will happen if HTTP_HOST isn't set. Do you think these warnings are showing on requests made through a command line? The HOST isn't usually set for those.

Anyway, fixing it should be as simple as replacing the line with something like this. Can you try this and reply if it works?

`if ( isset( $WPSC_HTTP_HOST ) == false || $WPSC_HTTP_HOST == '' || false === strpos( $permalink, $WPSC_HTTP_HOST ) ) {`

**Comment by marcomarsala** [comment]
Yes, I'm launching `php wp-cron.php` from a Linux shell.

**Comment by marcomarsala** [comment]
Site down with error HTTP 500 when refreshing the page after the cache was generated. Don't apply this fix.

**Comment by donnchawp** [comment]
The latest version of the plugin now checks if HTTP_HOST is set (in wp-cache-base.php) and if not sets $WPSC_HTTP_HOST to "" and disables caching so this warning shouldn't show up now.

**Comment by stodorovic** [comment]
@marcomarsala You can see #383. My advice is to you set "environment variables" before run php from shell. Also, maybe you can see this script: https://github.com/szepeviktor/debian-server-tools/blob/master/webserver/wp-cron-cli.sh

**Comment by stodorovic** [comment]
This issue is most likely fixed by #475 and other PRs.
