### ISSUE TITLE
php 7.1?

### ISSUE THREAD

**Issue by emo321** [Automattic/wp-super-cache#244]
Got error ‘PHP message: PHP Warning: A non-numeric value encountered in /home/xxxxxx/domains/xxxxxxxxxxxxxxxxxxx/public_html/wp-content/plugins/wp-super-cache/wp-cache-phase2.php on line 1285\n’

**Comment by donnchawp** [comment]
That's odd, but easily fixed. Does it show all the time?

**Comment by donnchawp** [comment]
If you're running the stable version of the plugin please edit wp-cache-phase2.php and look for the wp_cache_microtime_diff() function. 
Change the last line of that function so it reads:
`return (float)$b_sec - (float)$a_sec + (float)$b_dec - (float)$a_dec;`

You can see the change I've made here: https://github.com/Automattic/wp-super-cache/pull/245/files

That should fix the problem. Please reply if it does so I can close this bug and merge the fix.

**Comment by emo321** [comment]
This error appeared exactly every 15 minutes. I found out that it only occurs when I have add a page to feed. What's strange after turning off and re-enabling feed the error does not appear anymore. Thank you for the corrected code. Maybe it will be useful in the future

**Comment by donnchawp** [comment]
That is weird. I merged my code in #245 since it's the proper way to handle microtimes like this.
