### ISSUE TITLE
Prevent .gitkeep being removed.

### ISSUE THREAD

**Issue by mathieuhays** [Automattic/wp-super-cache#254]
I'm currently ignoring every file in the cache folder but the `.gitkeep` file in order to have the folder present in the repo without versioning the cache files.

I noticed that from time to time this file end up being deleted, probably by the `prune_super_cache` function.

Do you have anything against adding `.gitkeep` to the `$protected_directories` variable?

**Comment by donnchawp** [comment]
What the plugin should really do is add a filter to the $protected_directories variable so users can add items to it themselves..

**Comment by donnchawp** [comment]
@mathieuhays - I added a "wpsc_get_protected_directories" filter that you can use to change the list of directories. It's in master here if you want to give it a spin.

**Comment by mathieuhays** [comment]
It works a treat!
Thanks @donnchawp
