### ISSUE TITLE
PHP Notice upon deleting cached file

### ISSUE THREAD

**Issue by kraftbj** [Automattic/wp-super-cache#27]
Via Contents tab, attempting to delete a supercache file:

```
Deleting supercache file: www......com/index-https.html/
Notice: Array to string conversion in .../wp-includes/formatting.php on line 766
Notice: Array to string conversion in .../wp-includes/formatting.php on line 766
```

**Comment by momnt** [comment]
This is likely coming from using one of the esc_ functions on a variable meant to be a string, but turning up as an array

**Comment by alexsanford** [comment]
Just tried deleting a supercache file and didn't see the problem - http://cld.wthms.co/b97RDR

Closing this. Feel free to reopen with some additional info on how to reproduce if the error persists!
