### ISSUE TITLE
Fatal Error with Jetpack Beta Plugin

### ISSUE THREAD

**Issue by beaulebens** [Automattic/wp-super-cache#298]
I'm running the [Jetpack Beta](https://github.com/Automattic/jetpack-beta) plugin on a multi-site installation, and came across a fatal error that comes from WPSC trying to use a file/function in Jetpack.

The Jetpack Beta plugin works by basically installing an additional copy of Jetpack in a different directory (`jetpack-dev`) alongside your normal installation. Then the Beta plugin handles switching you over to using the `jetpack-dev` copy, and keeping it up to date with bleeding edge, specific branches from Github, whatever you pick.

WPSC has an extension that tries to use a function from Jetpack (`jetpack_is_mobile`) if it's available, but the way it looks for it causes Jetpack to be double-loaded if you're using the Beta plugin, and so you get a fatal error when the function is re-defined.

The problem happens in [this function](https://github.com/Automattic/wp-super-cache/blob/7833a914d8cfa31f48a0ce09251e8d4184fb307f/plugins/jetpack.php#L52), because that file _does_ in fact exist (as described above, you end up with 2 copies of the plugin on the filesystem), but it's not (intentionally) being loaded at the time (since the copy under `jetpack-dev` is already active).

I _think_ the only safe way to really do things here is just check for the existence of the `jetpack_is_mobile()` function, and don't do any dynamic loading of the file directly... or else look in `jetpack-dev` first, and then `jetpack` perhaps.

**Comment by beaulebens** [comment]
Note that when I was logged in, I didn't see any problem. I only see a problem (server hits a fatal, returns a 500) when I'm logged out and trying to view a Page on the site.

**Comment by dbtlr** [comment]
Assuming there isn't something weird related to this file needing to be loaded before the standard WordPress plugin load flow (I hear that is an actual thing), then it seems reasonable that we would only want mobile theme support if Jetpack is loaded and the mobile theme is enabled, anyway.

**Comment by donnchawp** [comment]
Or maybe that didn't fix it ..

**Comment by donnchawp** [comment]
Oh what fun this has turned out to be!

**Comment by donnchawp** [comment]
@beaulebens - just so you're clear on this. If jetpack dev is detected the Jetpack mobile detection code isn't loaded because it causes a fatal error. I don't think there's any way around this from the WP Super Cache side of things. Jetpack will need to add a check to that file to detect if it has already been loaded.
