### ISSUE TITLE
Missing / in .htaccess path.

### ISSUE THREAD

**Issue by sebas** [Automattic/wp-super-cache#299]
I am seeing the following problem, when there is the need to modify the rewrite rules the path to the .htaccess file is missing a /

It shows as 

/var/www/vhosts/xxx.com/httpdocs.htaccess

instead of

/var/www/vhosts/xxx.com/httpdocs/.htaccess

Thanks for your help.

**Comment by Crunchify** [comment]
+1 for this. Same issue here.

**Comment by kuaza61** [comment]
+1 for this. Same issue here.

**Comment by Crunchify** [comment]
Just FYI. v1.5.1 still has this issue. Attaching screenshot.
![screen shot 2017-07-19 at 8 52 45 pm](https://user-images.githubusercontent.com/8164601/28396989-651bb4a6-6cc4-11e7-9e76-2ca71e33b29e.png)

**Comment by donnchawp** [comment]
Can you try the small mod in #306? It just adds a trailing slash to the home_path variable which should fix this.

I can't replicate this issue on my sites, and it never showed up in testing.

**Comment by Crunchify** [comment]
Thanks @donnchawp. It worked.

<img width="695" alt="screen shot 2017-07-20 at 12 51 23 pm" src="https://user-images.githubusercontent.com/8164601/28431531-4474fda8-6d4a-11e7-868d-aff0da6e3421.png">

**Comment by sebas** [comment]
It worked for me too.

**Comment by donnchawp** [comment]
Fixed in #306 - thanks for testing it @Crunchify and @sebas!

**Comment by joshuaiz** [comment]
Can this fix get pushed to an updated stable version (e.g. 1.5.2)? It borked two of my clients' sites and 3 of my personal sites so I had to disable WPSC altogether.

**Comment by Crunchify** [comment]
+ for it. It would help to push new version 1.5.2 ASAP with other fixes so far :) @donnchawp

**Comment by donnchawp** [comment]
Yes, there will be a new version soon.

**Comment by joshuaiz** [comment]
@donnchawp Thanks for the push - I appreciate all the hard work you are doing!
