### ISSUE TITLE
mod_rewrite & nginx

### ISSUE THREAD

**Issue by kraftbj** [Automattic/wp-super-cache#30]
We need to borrow from core and stop the notices for nginx users.

**Comment by jeffwidman** [comment]
I'd certainly appreciate this.

**Comment by jom** [comment]
@kraftbj Are you talking about this one across the top when cache delivery is set to `expert`? It looks like core just provides [a link](https://codex.wordpress.org/Nginx) for setting up Nginx (which happens to include a snippet for WPSC, which is handy) in Permalink Settings.
<img width="1466" alt="screen shot 2017-10-26 at 3 15 49 pm" src="https://user-images.githubusercontent.com/68693/32057976-b30b9fb6-ba60-11e7-94b3-a7c6639c5587.png">

**Comment by donnchawp** [comment]
Interesting. In vars.php I found this:
`$is_nginx = (strpos($_SERVER['SERVER_SOFTWARE'], 'nginx') !== false);`

That would be a useful check to have before warning about .htaccess rules.
