### ISSUE TITLE
Critical Bug - Deactivate and Delete Blows Away wp-admin

### ISSUE THREAD

**Issue by juraisa** [Automattic/wp-super-cache#321]
Greetings, there is a critical bug in the latest release of this plugin, Deactivating the plugin and then Deleting it within wp-admin in a deactivated state will cause the wp-admin folder to be fully unlinked and removed.

I believe it is related to these commits

https://github.com/Automattic/wp-super-cache/commit/1b34fbd2068296300967723ec84aec0f39fb2835

https://github.com/Automattic/wp-super-cache/commit/57ac2773c58dc8919bbc7df2f3bf5c4824914234

when deactivated WPCACHEHOME no longer exists in the wp-config.php file, and since you are within /wp-admin/ I 'think' it is deciding that wp-admin is now WPCACHEHOME and as such unlinking the entire directory in the process of cleaning up. I've done multiple installs and had another independent wordpress dev confirm as well, assistance is appreciated.

**Comment by kraftbj** [comment]
Thanks for the report. I've confirmed it.

**Comment by Ipstenu** [comment]
FYI I closed the plugin in the directory to stop people from installing it. Once this is fixed, let me know and I'll see if we can push the fix ASAP.

**Comment by dbtlr** [comment]
I'm working on it now

**Comment by dbtlr** [comment]
Fix was pushed, just doing a round of tests to make sure all is well before we merge and deploy 1.5.3

**Comment by Otto42** [comment]
Plugin is live. Looks like it's rolling fine. Since this is a rare condition, I think we averted the worst here. But there may be some issues. I'll check the numbers after the update check in the morning and see how bad the impact is. I think it's in the 12 hour window, so, minimal.
