### ISSUE TITLE
Preload issue after 1.5.0 - wrong counting posts

### ISSUE THREAD

**Issue by stodorovic** [Automattic/wp-super-cache#326]
It's related to commit [Added post_count setting to be used by preload UI ](https://github.com/Automattic/wp-super-cache/commit/2b3a4779030187bbd9634f8e82a45eabc3e091b0)

Test of function [wp_count_posts](https://codex.wordpress.org/Function_Reference/wp_count_posts):
```php
$count = wp_count_posts();
echo $count->publish, PHP_EOL;

$count = wp_count_posts( 'post' );
echo $count->publish, PHP_EOL;

$count = wp_count_posts( 'page' );
echo $count->publish, PHP_EOL;

$count = wp_count_posts( 'product' );
echo $count->publish, PHP_EOL;
```
Output:
9
9
39
1053

## Usage

`<?php wp_count_posts( $type, $perm ); ?>`

## Parameters

**$type**
(string) (optional) Post type to count
Default: 'post' 

## SQL query
`SELECT post_status, COUNT( * ) AS num_posts FROM wp_posts WHERE post_type = 'post' GROUP BY post_status`

## Consequence:

```
15:27:45 28821 /wp-cron.php wp_cron_preload_cache: no more posts to get. Limit (9) reached.
15:27:45 28821 /wp-cron.php wp_cron_preload_cache: no more posts. scheduling next preload in 720 minutes.
```
Only first of 100 posts/pages/products are fetched.

Possible solution is usage of direct queries again (as in version 1.4.9).

**Comment by stodorovic** [comment]
Other solution for counting and possible replace for [this query](https://github.com/Automattic/wp-super-cache/blob/master/wp-cache.php#L3446-L3450):

```php
$args = array(
        'fields' => 'ids',
        'post_status' => 'publish',
        'post_type' => 'any',
        'posts_per_page' => 100,
);
  
$posts_query = new WP_Query( $args );
```

```
SELECT SQL_CALC_FOUND_ROWS  wp_posts.ID FROM wp_posts  WHERE 1=1  AND wp_posts.post_type IN ('post', 'page', 'attachment', 'product', 'books', 'lux_report', 'profiles' ) AND ((wp_posts.post_status = 'publish'))  ORDER BY wp_posts.post_date DESC LIMIT 0, 100
```

Then `$posts_query->found_posts` (SQL:`SELECT FOUND_ROWS()`) returns number of all posts. So, there are two queries (instead one direct SQL query), query time is similar, but it's more flexible.

Also, it's possible to we add filters for post_type (eg:_wp_cache_preload_post_types_) and orderby.

**Comment by donnchawp** [comment]
I'll revert it to the original SQL. That WP_Query is causing errors from my MySQL install (PHP Warning:  Error while sending QUERY packet.) and doing an explain on that SQL above shows it's not very kind to the database, requiring a filesort, again with my own server settings which are modest.

**Comment by donnchawp** [comment]
@stodorovic - can you take a look at #336? Reverting to the original SQL should allow you to preload all your content.

**Comment by stodorovic** [comment]
_Error while sending QUERY packet._ is often result of small session timeout. PHP code which runs preload request (cron task) could be longer than 30s (usual settings on many shared hosting). It isn't related only to this query. Solution for session timeout is:

`$GLOBALS['wpdb']->query( 'set session wait_timeout=300' );`

It should be started before preloading (I think that 5mins is enough). Or set some smaller value (60) after set_time_limit: 
https://github.com/Automattic/wp-super-cache/blob/master/wp-cache.php#L3406
https://github.com/Automattic/wp-super-cache/blob/master/wp-cache.php#L3468

Examples from other plugins:

https://github.com/wp-plugins/wysija-newsletters/blob/master/classes/WJ_Import.php#L250-L252
https://github.com/lifeinthegrid/duplicator/blob/master/classes/package/class.pack.database.php#L282-L284
You can see more examples in import/export/backup plugins.

Trouble with WP query is `SQL_CALC_FOUND_ROWS`.  It's often more efficient to run COUNT(*) as in our case #336 + SELECT statement with a LIMIT clause. So, direct replacement based on WP QUery is:

```php
$args = array(  
        'fields' => 'ids',
        'post_status' => 'publish',
        'post_type' => get_post_types( array( 'public' => true ) ),
        'no_found_rows' => true,
        'posts_per_page' => 100,
        'orderby' => 'ID',        
);

$posts_query = new WP_Query( $args );
```

SQL Query:
```
SELECT   wp_posts.ID FROM wp_posts  WHERE 1=1  AND wp_posts.post_type IN ('post', 'page', 'attachment', 'product', 'books', 'lux_report', 'profiles', 'portfolio') AND ((wp_posts.post_status = 'publish'))  ORDER BY wp_posts.ID DESC LIMIT 0, 100
```
Original query is:
```
SELECT ID FROM wp_posts WHERE post_type IN ('post','page','attachment','product','books','lux_report','profiles','portfolio') AND post_status = 'publish' ORDER BY ID DESC LIMIT 0, 100
```

```
mysql> explain SELECT wp_posts.ID FROM wp_posts  WHERE 1=1  AND wp_posts.post_type IN ('post', 'page', 'attachment', 'product', 'books', 'lux_report', 'profiles', 'portfolio') AND ((wp_posts.post_status = 'publish'))  ORDER BY wp_posts.ID DESC LIMIT 0, 100;
+----+-------------+----------+-------+------------------+---------+---------+------+------+-------------+
| id | select_type | table    | type  | possible_keys    | key     | key_len | ref  | rows | Extra       |
+----+-------------+----------+-------+------------------+---------+---------+------+------+-------------+
|  1 | SIMPLE      | wp_posts | index | type_status_date | PRIMARY | 8       | NULL |  363 | Using where |
+----+-------------+----------+-------+------------------+---------+---------+------+------+-------------+
1 row in set (0.00 sec)

mysql> explain SELECT ID FROM wp_posts WHERE post_type IN  ('post','page','attachment','product','books','lux_report','profiles','portfolio') AND post_status = 'publish' ORDER BY ID DESC LIMIT 0, 100;                                                          
+----+-------------+----------+-------+------------------+---------+---------+------+------+-------------+
| id | select_type | table    | type  | possible_keys    | key     | key_len | ref  | rows | Extra       |
+----+-------------+----------+-------+------------------+---------+---------+------+------+-------------+
|  1 | SIMPLE      | wp_posts | index | type_status_date | PRIMARY | 8       | NULL |  363 | Using where |
+----+-------------+----------+-------+------------------+---------+---------+------+------+-------------+
1 row in set (0.00 sec)
```

So, it's absolutely same as [original query](https://github.com/Automattic/wp-super-cache/blob/master/wp-cache.php#L3446)
