### ISSUE TITLE
Use Ajax count, but still can't display the count in real time

### ISSUE THREAD

**Issue by f2ex** [Automattic/wp-super-cache#330]
After using WP Super Cache, the Ajax count does not display properly on the page, but the log shows the count is successful and all previous counts are displayed after the cache is deleted.

WP Super Cache uses Simple cache. 

What is the problem? Thanks

**Comment by donnchawp** [comment]
Do you mean the count on the Contents page? Those figures aren't updated dynamically. You have to click the regenerate link to update them because the update is heavy - lots of files have to be checked.

**Comment by f2ex** [comment]
@donnchawp Yes , I used ajax count, but still can not update .

**Comment by donnchawp** [comment]
There isn't any AJAX in the plugin. You have to manually click the regenerate link to update the counts on the Contents page.
