### ISSUE TITLE
Cached page using ajax load more doesn't work

### ISSUE THREAD

**Issue by jorenvh** [Automattic/wp-super-cache#331]
I'm using your plugin in combination with ajax load more. But recently we are having more and more troubles using both of them together. Once a page got cached our content is not loading anymore and we do get the following responses:

XHR request: 200 ok with response: Error, could not verify WP nonce.

Console:

SyntaxError: Unexpected token E in JSON at position 1
    at JSON.parse (<anonymous>)
    at m.parseJSON (jquery.js:4)
    at Pc (jquery.js:4)
    at x (jquery.js:4)
    at XMLHttpRequest.b (jquery.js:4)
in ajax-load-more.min.js?ver=3.1.0:1

WP version: 4.7.5
Plugin version: 3.1.0 (I need to update I know & thats planned in the coming month)
WP super cache version: 1.4.9 (I need to update I know & tahts planned in the coming month)

So to wrap it up, the page that is using ajax load more implements an filter option & loads their contents using ajax. Once that page is cache it doesn't display any contents an throws the errors above. 

I'm not sure if the issue is related to WP super cache or ajax load more so I raised an issue here as well as at ajax load more.

Hope to hear from you.

**Comment by donnchawp** [comment]
Use the debug log to figure out if the ajax request is being cached. If it is, the plugin author should add the constant "DONOTCACHEPAGE" to stop the request from being cached.
