### ISSUE TITLE
Blank Page

### ISSUE THREAD

**Issue by guldoe** [Automattic/wp-super-cache#35]
Sometimes I have a problem with blank page, both front end and backend, when I install a plugin ... He shows me the following error.
The way to fix it is not valid for a share hosting since I do not have access to php.ini

Fatal error: Internal Zend error - Missing class information for in /usr/home/.../web/wp-content/plugins/wp-super-cache/wp-cache-base.php on line 5

**Comment by jnylin** [comment]
Am I right if I suppose you also use APC http://php.net/manual/en/book.apc.php?

**Comment by jnylin** [comment]
Related to #21

**Comment by kraftbj** [comment]
Yup, sounds like the same issue. Marking this as a duplicate and will follow up in #21.
