### ISSUE TITLE
.htaccess path wrong

### ISSUE THREAD

**Issue by fabianf1** [Automattic/wp-super-cache#350]
On one of the webhosts were I run a WordPress site the .htaccess path is wrong. 
WP-Super-Cache wants to edit the .htaccess file  in the following directory:

 **/home/strato/http/power/rid/85/xx/xxxxxxxx/htdocs/**

This is the value of the ```$home_path``` variable in the ```wpsc_update_htaccess_form function``` and also the value of ```$_SERVER[ 'DOCUMENT_ROOT' ]```. 

However, ```get_home_path()```returns:

**/mnt/web122/c1/xx/xxxxxxxx/htdocs/wordpress_main/**

This is the real directory and also used as the base path in the rewrite rules themselves.

This issue is caused by the following commit: aeeb1db06a5b0ad916adee04bc5df8dd2f5efd6f.
Reverting that commit, at least in the ```wpsc_get_htaccess_info()``` function, fixes the issue for me.

**Comment by donnchawp** [comment]
Bah. This is a minefield. How have you configured [WordPress to see the install](https://codex.wordpress.org/Giving_WordPress_Its_Own_Directory)? Is it using the current method, without a URL change, or the older one where siteurl and homeurl/WordPress URL are different?

**Comment by fabianf1** [comment]
I don't think that that does apply to my situation. The **/htdocs/wordpress_main/** folder is mapped to the root of my domain(e.g. http://example.com/). The **/htdocs/** folder itself does only contain directories that are mapped to the root or subdomains.

**Comment by donnchawp** [comment]
I'll need to recreate this sort of environment to test it. Unfortunately today's release hasn't changed the code so don't update the rewrite rules!

**Comment by fabianf1** [comment]
Interestingly, the rewrite rules themselves are correct. Only the path to the .htaccess file in the root folder is wrong since that commit. The path to the .htaccess file in the cache folder remains correct.

**Comment by donnchawp** [comment]
Yes, that's right, but obviously it needs to be more flexible to cope with environments like yours.

I wonder if it would make sense to add a setting to allow you to enter the correct path for the .htaccess file. As your host proves, there are some unusual setups out there.

**Comment by fabianf1** [comment]
It might be possible to use a setting to choose between, in my case:
* the folder containing the wordpress files, e.g. **/htdocs/wordpress_main/**
* the folder that could be the real root, e.g.**/htdocs/**
This choice should then only be presented if it might be the case that the WordPress files have been moved. 

A setting to manually enter the path is more flexible and would allow to take care of even more exotic configurations, but I don't now if that is necessary.

**Comment by LinnightL** [comment]
Any updates on this - facing the exact same issue

would be great to have the option of adjusting the htaccess path as there is for Cache Location

**Comment by donnchawp** [comment]
I have a PR in #507 you can try. Set $htaccess_path in wp-config.php or wp-cache-config.php and hopefully the plugin will edit the right .htaccess file. Does it?

I haven't added it to the admin page because it's unlikely to be an issue most people will run into.

**Comment by fabianf1** [comment]
Works for me! 👍
