### ISSUE TITLE
$cache_file may not be correctly initialised

### ISSUE THREAD

**Issue by cmangla** [Automattic/wp-super-cache#376]
https://github.com/Automattic/wp-super-cache/blob/7902634de526f5a024d121f6b7de50034cc0527f/wp-cache-phase1.php#L132

`$cache_filename` is a file name and `wpsc_get_realpath` seems to return `false` when given a file instead of a directory, so it seems `$cache_file` will not get initialised correctly. Same issue with the subsequent line.

When I enable logging I get "wpsc_get_realpath: directory does not exist - " messages. Seems to be due to this issue.

**Comment by stodorovic** [comment]
Hi @cmangla 

You are referenced my commit, but these lines aren't changed in this commit. I'm guessing that you want to reference:

https://github.com/Automattic/wp-super-cache/blob/master/wp-cache-phase1.php#L132-L133

It's helpful if you can send messages from debug log. Which is your current version of WPSC (1.5.5, github, ...) ?

**Comment by cmangla** [comment]
Yes, those are the lines I wanted to reference.

WPSC version 1.5.5.

Elided logs (omissions replaced by '...'):

```
13:36:34 5037 /wp-admin/index.php wp_cache_get_cookies_values: /^wp-postpass_|^comment_author_|^wordpress_logged_in_/ Cookie detected: wordpress_logged_in_...

13:36:34 5037 /wp-admin/index.php wp_cache_get_cookies_values: return: ...

13:36:34 5037 /wp-admin/index.php Caching disabled for logged in users on settings page.

13:36:34 5037 /wp-admin/index.php wp_cache_get_cookies_values: cached: ...

13:36:34 5037 /wp-admin/index.php wpsc_get_realpath: directory does not exist - /.../public_html/wp-content/cache/wp-cache-....php

13:36:34 5037 /wp-admin/index.php wpsc_get_realpath: directory does not exist - /.../public_html/wp-content/cache/meta/wp-cache-....php

13:36:34 5037 /wp-admin/index.php In WP Cache Phase 2

13:36:34 5037 /wp-admin/index.php Setting up WordPress actions

13:36:34 5037 /wp-admin/index.php Not caching wp-admin requests.
```

**Comment by donnchawp** [comment]
This is harmless because $cache_file is first used to serve wp-cache files from the old location. See [line 177](https://github.com/Automattic/wp-super-cache/blob/master/wp-cache-phase1.php#L177).

That if() check has an OR so it will succeed on the second condition if the cache file is present in the new location (supercache dirs).

I'll fix those two lines though, just to get rid of the warning.
