### ISSUE TITLE
WP Super Cache does not clear cache after a new post is published

### ISSUE THREAD

**Issue by ingilizcecin** [Automattic/wp-super-cache#387]
Hello, 
https://s.nimbus.everhelper.me/share/1120811/fuuyidaghx4xtmhizsop here you can see my WP Super Cache settings. 

According to these settings, is it normal that WP Super Cache doesn't clear the cached files of categories or do I have to use the option "Clear all cache files when a post or page is published or updated."?  

However, choosing the option to clear all the cache after each new post is not logical to me.

**Comment by stodorovic** [comment]
Hi @ingilizcecin 

At first look, your settings are fine. Could you enable debug mode (on super cache dashboard - Hata Ayıklama on your screenshot)? Then you try to create new post and please send here snippet from debug log related to it.

Regards,
Sasa

**Comment by ingilizcecin** [comment]
@stodorovic There are too many line in the log file. I hope I have choosen the related lines.

08:58:07 12995 /upload wpsc_get_realpath: directory does not exist - /home/ingilizm/public_html/wp-content/cache/wp-cache-c53a46ea0e4f153677b16e3a4b015500.php

08:58:07 12995 /upload wpsc_get_realpath: directory does not exist - /home/ingilizm/public_html/wp-content/cache/meta/wp-cache-c53a46ea0e4f153677b16e3a4b015500.php

08:58:07 12995 /upload In WP Cache Phase 2

08:58:07 12995 /upload Setting up WordPress actions

08:58:07 12995 /upload Created output buffer

08:58:07 12996 /wp-admin/admin-ajax.php wp_cache_get_cookies_values: cached: a5fe6097d239874c0314037b43928331

08:58:07 12996 /wp-admin/admin-ajax.php wp_cache_check_mobile: www.ingilizcecin.com443a5fe6097d239874c0314037b43928331

08:58:07 12996 /wp-admin/admin-ajax.php wpsc_get_realpath: directory does not exist - /home/ingilizm/public_html/wp-content/cache/wp-cache-0b473f7863481be68845afc6cfa328a1.php

08:58:07 12996 /wp-admin/admin-ajax.php wpsc_get_realpath: directory does not exist - /home/ingilizm/public_html/wp-content/cache/meta/wp-cache-0b473f7863481be68845afc6cfa328a1.php

08:58:07 12996 /wp-admin/admin-ajax.php In WP Cache Phase 2

08:58:07 12996 /wp-admin/admin-ajax.php Setting up WordPress actions

08:58:07 12996 /wp-admin/admin-ajax.php Not caching wp-admin requests.

08:58:07 12995 /upload wp_cache_post_edit: draft post, not deleting any cache files. status: inherit

08:58:07 12995 /upload wp_cache_post_edit: Clearing cache for post 46114 on post edit.

08:58:07 12995 /upload supercache dir: /home/ingilizm/public_html/wp-content/cache/supercache/www.ingilizcecin.com/2017-2018-11-12-sinif-secmeli-ingiliz-edebiyati-yillik-plani-46114/

08:58:07 12995 /upload wp_cache_post_id_gc post_id: 46114 https://www.ingilizcecin.com/2017-2018-11-12-sinif-secmeli-ingiliz-edebiyati-yillik-plani-46114/ clearing cache in /home/ingilizm/public_html/wp-content/cache/supercache/www.ingilizcecin.com/2017-2018-11-12-sinif-secmeli-ingiliz-edebiyati-yillik-plani-46114/.

08:58:07 12995 /upload wpsc_get_realpath: directory does not exist - /home/ingilizm/public_html/wp-content/cache/supercache/www.ingilizcecin.com/2017-2018-11-12-sinif-secmeli-ingiliz-edebiyati-yillik-plani-46114/

08:58:07 12995 /upload prune_super_cache: exiting as file/directory does not exist : /home/ingilizm/public_html/wp-content/cache/supercache/www.ingilizcecin.com/2017-2018-11-12-sinif-secmeli-ingiliz-edebiyati-yillik-plani-46114/

08:58:07 12995 /upload wp_cache_post_id_gc clearing cache in /home/ingilizm/public_html/wp-content/cache/supercache/www.ingilizcecin.com/page/.

08:58:07 12995 /upload Post change: supercache enabled: deleting cache files in /home/ingilizm/public_html/wp-content/cache/supercache/www.ingilizcecin.com/

08:58:07 12995 /upload rebuild_or_gc: rename file to /home/ingilizm/public_html/wp-content/cache/supercache/www.ingilizcecin.com/index-https.html.gz.needs-rebuild

08:58:07 12995 /upload rebuild_or_gc: rename file to /home/ingilizm/public_html/wp-content/cache/supercache/www.ingilizcecin.com/index-https-mobile.html.needs-rebuild

08:58:07 12995 /upload rebuild_or_gc: rename file to /home/ingilizm/public_html/wp-content/cache/supercache/www.ingilizcecin.com/index-https-mobile.html.gz.needs-rebuild

08:58:07 12995 /upload rebuild_or_gc: rename file to /home/ingilizm/public_html/wp-content/cache/supercache/www.ingilizcecin.com/index-https.html.needs-rebuild

08:58:07 12995 /upload wp_cache_post_change: not deleting front static page.

08:58:07 12995 /upload wp_cache_post_change: checking /home/ingilizm/public_html/wp-content/cache/meta/

08:58:07 12995 /upload wpsc_get_realpath: directory does not exist - /home/ingilizm/public_html/wp-content/cache/supercache/www.ingilizcecin.com//category/lise/

08:58:07 12995 /upload prune_super_cache: exiting as file/directory does not exist : /home/ingilizm/public_html/wp-content/cache/supercache/www.ingilizcecin.com//category/lise/

08:58:07 12995 /upload wpsc_post_transition: deleting category: /home/ingilizm/public_html/wp-content/cache/supercache/www.ingilizcecin.com//category/lise/

08:58:07 12995 /upload wpsc_get_realpath: directory does not exist - /home/ingilizm/public_html/wp-content/cache/supercache/www.ingilizcecin.com//2017-2018-11-12-sinif-secmeli-ingiliz-edebiyati-yillik-plani/

08:58:07 12995 /upload prune_super_cache: exiting as file/directory does not exist : /home/ingilizm/public_html/wp-content/cache/supercache/www.ingilizcecin.com//2017-2018-11-12-sinif-secmeli-ingiliz-edebiyati-yillik-plani/

08:58:07 12995 /upload wpsc_post_transition: deleting post: /home/ingilizm/public_html/wp-content/cache/supercache/www.ingilizcecin.com//2017-2018-11-12-sinif-secmeli-ingiliz-edebiyati-yillik-plani/

08:58:09 12995 /upload wp_cache_post_edit: Already processed post 46114.

08:58:09 12995 /upload Not caching POST request.

08:58:09 12995 /upload wp_cache_maybe_dynamic: returned $buffer

08:58:09 13000 /user/mammeeee/?profiletab=main wp_cache_get_cookies_values: return: 

08:58:09 13000 /user/mammeeee/?profiletab=main No wp-cache file served as user agent rejected.

**Comment by stodorovic** [comment]
It seems OK. category/lise/ is deleted from cache. Front page is marked for rebuilding at next request (Cache will be send and then rebuild).

PS. You can remove this log. I copied it and I'll try to check it again today when I've more time.

**Comment by ingilizcecin** [comment]
@stodorovic Thanks a lot for your interest. 
Although, it say the category is deleted from cache, it still appears to cached. I have to manually clear the category from the cache.

**Comment by stodorovic** [comment]
I think that I see issue. Function `wpsc_delete_cats_tags` doesn't use WP API to get URL/directory. Related code: https://github.com/Automattic/wp-super-cache/blob/master/wp-cache-phase2.php#L1334-L1341

So, your log shows `wpsc_post_transition: deleting category: ... /category/lise/`. On website, I see `.../ingilizce-yillik-planlar/lise/`. You can try to change line:
`prune_super_cache ( get_supercache_dir() . $category_base . $cat->slug . '/', true );`
with
`prune_super_cache ( get_supercache_dir() . wp_make_link_relative( get_term_link( $cat ) ) . '/', true );`

If it works, I'll try to make PR, but it needs more testing (previous code doesn't work for sub-directory installation).

**Comment by ingilizcecin** [comment]
So, what shall I do now? According to your explanation, WP Super Cache needs an update to fix this issue. 

What is PR by the way? 😳

**Comment by stodorovic** [comment]
Yes, it's issue in the code. I'll try to replace `$category_base . $cat->slug` with function [get_term_link](https://developer.wordpress.org/reference/functions/get_term_link/). I see more similar snippets there. 

PR is [pull request](https://help.github.com/articles/about-pull-requests/). I should make changes in PHP code, test them and create [new PR here](https://github.com/Automattic/wp-super-cache/pulls). After reviewing changes from other developers, they will merge it into repository. (then you can download beta version) I can't estimate when beta version (with fix) will be released. I hope in couple weeks.

I don't know how is your PHP experience. I hope that helps for better understanding.

**Comment by stodorovic** [comment]
Hi @ingilizcecin 

I just created PR #389. You could test it if you want. You should replace file wp-cache-phase2.php (/wp-content/plugins/wp-super-cache) with https://github.com/stodorovic/wp-super-cache/blob/f338ef7a487b2c7e49afe0ae82f726080f3ee0bd/wp-cache-phase2.php My first test is OK, but it needs more testing and improvements.

**Comment by ingilizcecin** [comment]
@stodorovic Hello, when will they release an update to fix this issue?
