### ISSUE TITLE
Unsuccessful wp_cache_replace_line call should not write directly on output

### ISSUE THREAD

**Issue by janrenn** [Automattic/wp-super-cache#388]
This should use `trigger_error` and not to write on output directly. It cannot be handled with `error_reporting` and compromises server paths when error occurs during frontend rendering procedure.

```
function wp_cache_replace_line($old, $new, $my_file) {
	if ( @is_file( $my_file ) == false ) {
		return false;
	}
	if (!is_writeable_ACLSafe($my_file)) {
		echo "Error: file $my_file is not writable.\n";
		return false;
	}
```

**Comment by donnchawp** [comment]
Thanks @janrenn for the bug report and fix.
