### ISSUE TITLE
White / Blank Screen

### ISSUE THREAD

**Issue by johnw6761** [Automattic/wp-super-cache#398]
I am having the white screen issue after turning caching on. I have tried to follow steps others recommend of uninstalling the plugin and reinstalling. 

The issue is there is the uninstall instructions mention editing wp-config and .htaccess however when I open both these files there is no mention of wp super cache so there is nothing to delete?

I remove every trace of the plugin I can find but when I re install I get the same issues.

**Comment by gui1porpis** [comment]
The problem is in **/wp-content/plugins/wp-super-cache/plugins/searchengine.php**, rename and wait for a new fix.

**Comment by johnw6761** [comment]
I tried renaming searchengine.php which didnt work.

I updated the plugin and still didnt work?

**Comment by donnchawp** [comment]
What do you see in your php error log? Do you see any fatal errors?

**Comment by johnw6761** [comment]
No nothing

**Comment by johnw6761** [comment]
Actually this

**Comment by johnw6761** [comment]
Fatal error: Call to undefined function apply_filters() in /websites/123reg/LinuxPackage23/de/16/2_/de162.co.uk/public_html/helenkeeble.co.uk/wordpress/wp-content/plugins/wp-super-cache/wp-cache-phase1.php on line 199

**Comment by donnchawp** [comment]
Oh, what version of WordPress are you using? This might be because you're using an old version of WordPress that doesn't load as much as the current version does. :(

**Comment by donnchawp** [comment]
For the moment, change line 199 to this and it'll work again:
`$rss_types = array( 'application/rss+xml', 'application/rdf+xml', 'application/atom+xml' );`

We'll get another update out soon.

**Comment by johnw6761** [comment]
That worked perfectly thank you!
