### ISSUE TITLE
Wrong italian translation for "Make known users anonymous so they're served supercached static files."

### ISSUE THREAD

**Issue by DrLightman** [Automattic/wp-super-cache#414]
`Make known users anonymous so they're served supercached static files.`

Now in italian is translated as:

`Imposta gli utenti conosciuti come autonomi così gli verrà fornito i file statici dalla cache.`

Instead it should be:

`Imposta gli utenti conosciuti come anonimi così gli verranno forniti i file statici dalla cache.`

**Comment by donnchawp** [comment]
Thank you for the translation. Can you visit [the translation page](https://translate.wordpress.org/projects/wp-plugins/wp-super-cache) and submit it there?
