### ISSUE TITLE
clear_post_supercache($post_id) - is it ok to use in another plugin or theme to force delete the cache of a post?

### ISSUE THREAD

**Issue by DrLightman** [Automattic/wp-super-cache#417]
Hello, sorry if I'm using this section to make a question that is more for the support forum maybe.

Is it ok to use the function `clear_post_supercache()` to force delete at 100% the cache of a post in a cli script or another plugin or theme?

I was laso using wp_cache_post_change() in the past, but it may not delete the cache in some cases?

**Comment by donnchawp** [comment]
Definitely. As long as the plugin is configured correctly and the function exists then you can use it.

**Comment by DrLightman** [comment]
FYI, I'm having issues with this since it's not clearing it, wpsc static files .html and .html.gz are still in the post's directory. It's behaving like this in either 1.5.7.1 and 1.5.8.

In the past I used `wp_cache_post_change` and it worked too, but it's not working either now.

I'm trying to do some debug.

**Comment by DrLightman** [comment]
`09:40:38 7856  wpsc_get_realpath: directory does not exist - D:\MySites\wptest.local\wp-content/cache/supercache/example-post-to-delete/`

Mmm I think it's missing the blogurl slug (`wptest.local` in my setup) between `supercache` and `example-post-to-delete`, it may be related to the fact that I'm calling this from a CLI script and not via apache request?

**Comment by DrLightman** [comment]
Ok i think my issue starts here:

`$dir = preg_replace( '/:.*$/', '',  $WPSC_HTTP_HOST ) . $uri; `

Because in CLI $WPSC_HTTP_HOST is empty.
