### ISSUE TITLE
WP Super Duper Total Cache with Minify and Google PageSpeed

### ISSUE THREAD

**Issue by galbaras** [Automattic/wp-super-cache#42]
I love WP Super Cache and use it on all my sites, along with another plugin called Better WP Minify. Together, these plugins make sites very fast and create an almost perfect solution for speeding up sites.

Alas, BWP Minify has not been updated in a while, lacks HTML minification, doesn't prefetch and merge external resources and is not integrated into Super Cache, which requires more manual actions than would be necessary otherwise.

Also, Google PageSpeed still makes comments about cache control, vary headers and other things (like KeepAlive), which I supplement manually through .htaccess.

It would be great if WP Super Cache combined all these things into one magnificent plugin.

**Comment by lkraav** [comment]
Take a look at Zen Cache Pro. It would take a ton of time for WP Super Cache to gain many of these critical features you're listed. The development pace here is snail like, because this project doesn't seem to be a priority. Up to you if you want to wait a few years for WPSC to catch up on anything, of which nothing is even guaranteed.

**Comment by kraftbj** [comment]
Coming at it from a different angle than @lkraav, WPSC isn't supposed to be a One Plugin to Rule Them All—the aim of is a solid caching solution when more robust server-side offerings aren't possible or desirable, not a one-stop shop for performance. 

Marking this wontfix as out of scope per the project's aims.

PageSpeed issues about other issues are valid, though. If you could open a ticket outlining the suggestions from PageSpeed, we can look at feasibility to implement them noting the variety of server environments needing to be accounted for.
