### ISSUE TITLE
CPT with rewrite false clears complete cache

### ISSUE THREAD

**Issue by barrykooij** [Automattic/wp-super-cache#45]
If you've got a custom post type that has rewrite set to `false`, WP Super Cache clears the complete cache.

I believe this is happening because `get_current_url_supercache_dir` is stripping out the default WP rewrite and because of this the `$dir` because the root of the cache dir.

The content of `$permalink = trailingslashit( str_replace( get_option( 'home' ), '', post_permalink( $post_id ) ) );` (https://github.com/Automattic/wp-super-cache/blob/master/wp-cache-phase2.php#L1107) is `/?post_type=dlm_download&p=26/`. 

The content of `$dir = get_current_url_supercache_dir( $post_id );` is `/vagrant/download-monitor/wp-content/cache/supercache/lamp.dev/download-monitor/`. As you can see it completely strips of the permalink.

Since this CPT has no rewrite and no single I believe it shouldn't be cached at all. I think a check should be created checking if the result of `get_current_url_supercache_dir` isn't equal to the root cache dir.

**Comment by barrykooij** [comment]
Any update on this?

**Comment by kraftbj** [comment]
#66 will return out early if the two dirs match, which should resolve the immediate problem. I'd like to leave this open to audit where we can short-circuit the processes earlier for posts in this situation.

@barrykooij does #66 resolve it for you? Thanks for your patience!
