### ISSUE TITLE
Fatal error on wp-cache-phase2.php:1696 only on posts (not pages) 

### ISSUE THREAD

**Issue by webdados** [Automattic/wp-super-cache#454]
I'm getting this error on PHP 7.0.25
`
<b>Fatal error</b>:  Uncaught Error: Cannot use object of type WP_Query as array in /.../wordpress/wp-content/plugins/wp-super-cache/wp-cache-phase2.php:1696
--
  | Stack trace:
  | #0 /.../wordpress/wp-content/plugins/wp-super-cache/wp-cache-phase2.php(1192): wp_cache_post_id()
  | #1 /.../wordpress/wp-content/plugins/wp-super-cache/wp-cache-phase2.php(542): wp_cache_shutdown_callback()
  | #2 [internal function]: wp_cache_ob_callback('&lt;!DOCTYPE html&gt;...', 9)
  | #3 /.../wordpress/wp-includes/functions.php(3721): ob_end_flush()
  | #4 /.../wordpress/wp-includes/class-wp-hook.php(298): wp_ob_end_flush_all('')
  | #5 /.../wordpress/wp-includes/class-wp-hook.php(323): WP_Hook-&gt;apply_filters('', Array)
  | #6 /.../wordpress/wp-includes/plugin.php(453): WP_Hook-&gt;do_action(Array)
  | in <b>/.../wordpress/wp-content/plugins/wp-super-cache/wp-cache-phase2.php</b> on line <b>1696</b><br />
`
Is there any other information I can provide in order to help identifying the problem?

**Comment by stodorovic** [comment]
Thank you for reporting this.

I didn't see it on my installations and it's helpful if you can send more details how to reproduce it. I mean what kind of page is it (custom post type, comment, ...), theme,...

As quick workaround you can replace [line 1696 ](https://github.com/Automattic/wp-super-cache/blob/master/wp-cache-phase2.php#L1694) with:
`if (is_singular() && !empty($posts) && is_array($posts) ) return $posts[0]->ID;`

**Comment by webdados** [comment]
As a said on the thread title, it's only in posts, not pages (or CPTs).

Can we expect a fix on a new release?

**Comment by stodorovic** [comment]
Please send more details about theme/plugins. It's possible that theme or some plugin overrides WP global variable `$posts`. Global variable `$posts` should be array. Snippets from WP core:

[wp-includes/class-wp.php](https://github.com/WordPress/WordPress/blob/master/wp-includes/class-wp.php#L540-L578):
```php
        /**
         * Set up the WordPress Globals.
         *
         * The query_vars property will be extracted to the GLOBALS. So care should
         * be taken when naming global variables that might interfere with the
         * WordPress environment.
         *
         * @since 2.0.0
         * @access public
         *
         * @global WP_Query     $wp_query
         * @global string       $query_string Query string for the loop.
         * @global array        $posts The found posts.
	 * .....
         */
        public function register_globals() {
	.....
		$GLOBALS['posts'] = & $wp_query->posts;
	.....
	}
```
[wp-includes/class-wp-query.php](https://github.com/WordPress/WordPress/blob/master/wp-includes/class-wp-query.php#L86-L92):
```php

        /**
         * List of posts.
         *
         * @since 1.5.0
         * @access public
         * @var array
         */
        public $posts;
```

So, I'll check which how we can improve code, but I'm afraid that isn't issue related only to WPSC. It's possible that some PHP template uses `$posts` as variable (which is reserved for WP core) and it could make a lot of side effects in WP core.

**Comment by webdados** [comment]
I'm getting this while developing a new theme. Let me check it out, and get back to you, because I might be doing something wrong.

Anyway, you could apply the quick fix anyway :-)

**Comment by webdados** [comment]
`I'm getting this while developing a new theme.`
Ignore this. I was working on two projects at the same time.

This is happening with the HIGO theme: https://themeforest.net/item/higo-a-responsive-wordpress-blog-theme/20453938
I've made the following tests:
- Only Higo and WP Super Cache active: the error is there
- Only Twenty Seventeen and WP Super Cache active: the error is NOT there

I'm going to try to debug this a little further by going through the theme code and I'll get back to you if I reach any conclusion. Anyway, this seems like a theme problem.

**Comment by webdados** [comment]
Got it.

The problem is on themes/higo/sections/footer-posts.php line 40.

![image](https://user-images.githubusercontent.com/6853605/33656160-1f79a2de-da6d-11e7-947a-76ad885cf9f4.png)

For the meantime, I'm going to override this file on my child theme and change the variable name.

I'm also going to report this to the theme author.
