### ISSUE TITLE
Broken HTML code and other issues (WPSC settings) after merging PR #446

### ISSUE THREAD

**Issue by stodorovic** [Automattic/wp-super-cache#459]
There are some mistakes. Couple examples for now:

`esc_html_e( 'You or an administrator must disable this. See the <a href="http://php.net/features.safe-mode">safe mode manual page</a> for further details. This cannot be disabled in a .htaccess file unfortunately. It must be done in the php.ini config file.', 'wp-super-cache' );`
Result:
`You or an administrator must disable this. See the &lt;a href=&quot;http://php.net/features.safe-mode&quot;&gt;safe mode manual page&lt;/a&gt; for further details. This cannot be disabled in a .htaccess file unfortunately. It must be done in the php.ini config file.`

`esc_html__( 'A custom url or permalink structure is required for this plugin to work correctly. Please go to the <a href="options-permalink.php">Permalinks Options Page</a> to configure your permalinks.', 'wp-super-cache' );`
Result:
`A custom url or permalink structure is required for this plugin to work correctly. Please go to the &lt;a href=&quot;options-permalink.php&quot;&gt;Permalinks Options Page&lt;/a&gt; to configure your permalinks.`

So, PR #446 replaces `__` with `esc_html__` in many cases when it shouldn't be replaced. Also, it removes `echo` in couple cases and prevent output of some HTML tags.

Screenshot (broken HTML tags):
![wpsc-settings-broken-html1](https://user-images.githubusercontent.com/15647032/33016054-4d85dd28-cded-11e7-8eb3-ac803082528f.PNG)

**Comment by stodorovic** [comment]
Possible solutions could be:

`printf( esc_html__( 'You or an administrator must disable this. See the %1$ssafe mode manual page%2$s for further details. This cannot be disabled in a .htaccess file unfortunately. It must be done in the php.ini config file.', 'wp-super-cache' ) , '<a href="http://php.net/features.safe-mode">', '</a>'));`

or something like this, but it requires changing all translations.

**Comment by stodorovic** [comment]
@timse201 Please help us to fix it. It's consequence of your PR #446

**Comment by timse201** [comment]
yes, will do it today.

i prefer to handle urls outside of translation strings. its safer

**Comment by stodorovic** [comment]
Yes, I agree. And you submit previous PR without detail testing. There are two cases:

- HTML tag is on the end of line. We could add echo or something like this.
- HTML code is inside translation string. It requires changes in all language files. I'm not sure which is correct form. I proposed `printf` and adding HTML code as placeholders %1, %2,... It's often way in many plugins.

What you think?

**Comment by timse201** [comment]
i agree.
this will enhance readability and this should prevend my mistake that i didnt see some second echos in some lines.

**Comment by timse201** [comment]
some lines are
_e( " Make sure they appear before any existing WordPress rules. ", 'wp-super-cache' ) . "</p>";
			echo "<div style='overflow: auto; width: 800px; height: 400px; padding:0 8px;color:#9f6000;background-color:#feefb3;border:1px solid #9f6000;'>";

think it will not impact performance if we just eliminate these echos and close php and start it again if needed
so we have an additional readability enhancement

whats your opinion?

**Comment by stodorovic** [comment]
Hmm... I'm not sure that closing/opening tags is the best approach.

Example for lines https://github.com/Automattic/wp-super-cache/blob/master/wp-cache.php#L3106-L3108:

```php
printf( '<p>%1$s <code>%2$s.htaccess</code> %3$s %4$s</p>',
	esc_html__( 'To serve static html files your server must have the correct mod_rewrite rules added to a file called', 'wp-super-cache' ),
	$home_path,
	esc_html__( 'You can edit the file yourself. Add the following rules.', 'wp-super-cache' ),
	esc_html__( 'Make sure they appear before any existing WordPress rules.', 'wp-super-cache')
);
```
It's more clear for me to printf show entire paragraph. I'm not sure which is the best coding standard.
@donnchawp What you think?

**Comment by timse201** [comment]
true ;D

as i said some lines ;)

**Comment by stodorovic** [comment]
Other case - https://github.com/Automattic/wp-super-cache/blob/master/wp-cache.php#L213

```php
printf( esc_html__( 'You or an administrator may be able to make it work by changing the group owner of the plugin scripts to match that of the web server user. The group owner of the %1$s/cache/ directory must also be changed. See the %2$s for further details.', 'wp-super-cache' ),
	WP_CONTENT_DIR,
	'<a href="http://php.net/features.safe-mode">' . esc_html__( 'safe mode manual page', 'wp-super-cache' ) . '</a>'
);
```
I tried couple variations but it seems as more readable than other.

**Comment by timse201** [comment]
hello?
and again i wrote some lines
not all lines.....

**Comment by stodorovic** [comment]
Yes, it isn't related to all lines. But there are maybe 20-30 occurrences which we need to fix. :worried:

I'm not sure which is the best approach for URLs inside `esc_html__`. There are couple variants: https://wordpress.stackexchange.com/questions/260512/how-to-print-translation-supported-text-with-html-url I tried to check all variants and _Method-3_ seems as good choice.

**Comment by timse201** [comment]
sure but please red carefully...

some lines are
`_e( " Make sure they appear before any existing WordPress rules. ", 'wp-super-cache' ) . "</p>";`
`echo "<div style='overflow: auto; width: 800px; height: 400px; padding:0 8px;color:#9f6000;background-color:#feefb3;border:1px solid #9f6000;'>";`

think it will not impact performance if we just eliminate these echos and close php and start it again if needed
so we have an additional readability enhancement

whats your opinion?

**Comment by stodorovic** [comment]
```php
printf( '<p>%1$s <code>%2$s.htaccess</code> %3$s %4$s</p>',
	esc_html__( 'To serve static html files your server must have the correct mod_rewrite rules added to a file called', 'wp-super-cache' ),
	esc_html( $home_path ),
	esc_html__( 'You can edit the file yourself. Add the following rules.', 'wp-super-cache' ),
	esc_html__( 'Make sure they appear before any existing WordPress rules.', 'wp-super-cache')
);
?>
<div style='overflow: auto; width: 800px; height: 400px; padding:0 8px;color:#9f6000;background-color:#feefb3;border:1px solid #9f6000;'>
<?php
```

and

```php
printf( '<p>%1$s <code>%2$s.htaccess</code> %3$s %4$s</p>',
	esc_html__( 'To serve static html files your server must have the correct mod_rewrite rules added to a file called', 'wp-super-cache' ),
	esc_html( $home_path ),
	esc_html__( 'You can edit the file yourself. Add the following rules.', 'wp-super-cache' ),
	esc_html__( 'Make sure they appear before any existing WordPress rules.', 'wp-super-cache')
);
echo '<div style="overflow: auto; width: 800px; height: 400px; padding:0 8px;color:#9f6000;background-color:#feefb3;border:1px solid #9f6000;">';
```

It's same for me (and difference in performance are in microseconds). It's possible that _you are right_ that first variant is more readable in editor. So, I vote for first variant.

Anyway, we could wait for @donnchawp feedback. Also, we should create more PRs to we can easy review/merge code.

**Comment by donnchawp** [comment]
@stodorovic - thank you for spotting that issue with esc_html.

I don't think we can use something like `<p>%1$s <code>%2$s.htaccess</code> %3$s %4$s</p>` because some languages will have a different word order. That string above will have to be translated too.

Unfortunately I think the best solution for the translators is keeping the sentences separate.

I'll go over all the changes in that PR tomorrow testing them, and fixing them.

**Comment by donnchawp** [comment]
I think the safest thing to do right now is revert #446 so it can be fixed correctly.
