### ISSUE TITLE
Cache should clear if a comment is trashed

### ISSUE THREAD

**Issue by geoidesic** [Automattic/wp-super-cache#466]
Currently you have to manually clear the cache after moving any comments to the trash.

**Comment by dmackinn** [comment]
@geoidesic 

I'm not able to replicate this issue using WP 4.9.1 and the Twenty Seventeen theme.

**Comment by donnchawp** [comment]
I can't replicate this either. Can you enable debugging in the plugin and check what happens when you trash a comment?

**Comment by geoidesic** [comment]
Hi. I won't be able to now as unfortunately we gave up on Super Cache – mostly for other reasons; which is that it seemed hugely complicated to get it to play nice with twitter feeds and other dynamic elements. It ended up being easier just writing our own caching functions and optimising our code. I'll re-open this if we end up going this route at a later time and it's still an issue.
