### ISSUE TITLE
dynamic cache: expected to be a reference, value given

### ISSUE THREAD

**Issue by Dravon5X** [Automattic/wp-super-cache#470]
Hello

1.I want to use dynamic content (example 1 in dynamic-cache-test.php) but it don't work, from error log:
`PHP Warning:  Parameter 1 to dynamic_cache_test_filter() expected to be a reference, value given in domain.com/wp-content/plugins/wp-super-cache/wp-cache-phase1.php on line 457`

2.for Example 2 (dynamic buffer) it is
`PHP Warning:  Parameter 1 to dynamic_output_buffer_test() expected to be a reference, value given in domain.com/wp-includes/class-wp-hook.php on line 286`

3.the "secret placeholder tag" need to be secret? because if yes, anyone can see it when going to
`domain.com/wp-content/cache/supercache/domain.com/index-https.html`
it will show page with "secret" placeholder tag. Or this is result from the error above?

**Comment by donnchawp** [comment]
Thanks for the report. This is an unintended side effect of using call_user_func_array() in the do_cacheaction() function.

Hmm, I think you're right about the secret placeholder tag. I think the only way around that is to put the cache directory in a non-web-accessible location. Since you're using dynamic content all the files have to be served by PHP any way.

**Comment by Dravon5X** [comment]
Well as this plugin is creating whole cache folder including .htaccess, just inserting "deny from all" for Simple cache delivery method will be enough, and when switchng to Expert it will be removed.

**Comment by donnchawp** [comment]
Thanks @Dravon5X. I fixed the parameters, and added a note to the plugin to hide the cache to protect the secret tag.

**Comment by Dravon5X** [comment]
Two things:

1. only second method is working, method DYNAMIC_CACHE_TEST_TAG is not working. It will hide the secret tag, but won't output anything, nothing in error_log

2. there is **major** security and usability flaw, that after I delete cache, first visitor will see secret tag
