### ISSUE TITLE
Secret TAG from dynamic cache is visible

### ISSUE THREAD

**Issue by Dravon5X** [Automattic/wp-super-cache#490]
Hello

there is **major** security and usability flaw - after cache deletion, first visitor will see secret tag. Only 2nd and next visitors will see correct replacement of Secret TAG.

Please note method DYNAMIC_CACHE_TEST_TAG is not working at all, consider this when testing.

**Comment by donnchawp** [comment]
Do you have "Enable dynamic caching." checked in the advanced settings page? Without that checked the first request will show the tag.

**Comment by donnchawp** [comment]
The DYNAMIC_CACHE_TEST_TAG example works for me. I have "dynamic caching" enabled.

I cannot reproduce the problem you're seeing.

**Comment by Dravon5X** [comment]
I had enabled "Enable dynamic caching" of course. To eliminate showing TAG first time, after enabling "Enable dynamic caching" I need alwaya go and delete cache on Contents page.

**Comment by hawkmusician** [comment]
As Dravon5X said, "after cache deletion, first visitor will see secret tag. Only 2nd and next visitors will see correct replacement of Secret TAG." 

- Enable dynamic caching is on.
- Late Init is on. 

First load thus shows secret tag and is a security issue.
