### ISSUE TITLE
DYNAMIC_CACHE_TEST_TAG doesn't work

### ISSUE THREAD

**Issue by Dravon5X** [Automattic/wp-super-cache#493]
Hi

I'm not sure if somebody is reading messages when I wrote it to closed issue, so here again.

For me is not working DYNAMIC_CACHE_TEST_TAG, it will hide the secret key but no output instead. I just enter secter tag to dynamic-cache-test.php, can anyone reproduce? I'm using php 7.2

**Comment by donnchawp** [comment]
It worked for me. The best thing you can do is debug it on your server. Add error_log() or wp_cache_debug() statements to the plugin and see what code is being executed, and what isn't.
