### ISSUE TITLE
Wp super cache does not work

### ISSUE THREAD

**Issue by vaprub** [Automattic/wp-super-cache#502]
The wp super cache plugin does not work, cache checking does not work. Pages do not match! Temporary stamp is different or was not found! The shared cache is also not created, when checking copies, 3 copies of the main page are created and running.
Page not cached by WP Super Cache. Blank Page. Check output buffer usage by plugins.
Page not cached by WP Super Cache. No closing HTML tag. Check your theme.
In the source code of the page, if you see through the Developer Console <html> and </html>

**Comment by vaprub** [comment]
After turning off all the plugins and changing the theme, caching also does not work

**Comment by stodorovic** [comment]
Hi @vaprub 

It seems that output buffering doesn't work. It's possible that's started by other process. I see your (duplicated) issue on wp.org. If you contact me via slack (on wordpress.org), I'll try to help you.

**Comment by donnchawp** [comment]
Probably an issue on your server as the cache tester does work.
