### ISSUE TITLE
After migrating wordpress website "Fatal error: Cannot redeclare gzip_accepted() (previously declared in..."

### ISSUE THREAD

**Issue by Hank61** [Automattic/wp-super-cache#512]
After migrating my wordpress website from a sub-domain to the main domain I received the following error:
Fatal error: Cannot redeclare gzip_accepted() (previously declared in /home5/pessolut/public_html/dev/wp-content/plugins/wp-super-cache/wp-cache-phase2.php:4) in /home5/pessolut/public_html/wp-content/plugins/wp-super-cache/wp-cache-phase2.php on line 9

So I deleted the WP Super Cache plugin and reinstalled it.  But no cigar, same error.  There were no issues prior to migrating and no changes were made to the website.  Note I still have the original sub domain files and folders if that helps?

Any help would be greatly appreciated.

Sincerely,

Jeff

**Comment by kraftbj** [comment]
Hi Jeff,

What is the relationship between the /dev/ site and the one at /wp-content/ itself? Do they share a common drop-in plugin in wp-content that both point to /dev/wp-content/?

My initial guess is something like that is calling in the /dev/wp-content/ file before your main site is calling its version of WPSC.

**Comment by Hank61** [comment]
Thanks for your reply.  I resolved the problem by following the instructions on "How to uninstall WP Super Cache" located on the "Installation" tab  of the WP Super Cache documentation.  It requires jumping through quite a few hoops so I'm wondering why the developer wouldn't include these operations in the automatic uninstall of their product by default.  It would save us users a lot of wasted time and grief.
Sincerely,
Jeff

**Comment by donnchawp** [comment]
The plugin automatically does everything in that list but sometimes it doesn't work.
