### ISSUE TITLE
Admin bar not visible in Jupiter theme

### ISSUE THREAD

**Issue by dudlaj** [Automattic/wp-super-cache#514]
Hello I found a bug accidently. The wordpress admin bar is not visible in Jupiter theme when super cache is activated.
Jupiter 6.0.2 - latest version super cache.
Thx for great plugin btw 
dUDLAJ

**Comment by kraftbj** [comment]
Howdy,

Depending on your settings, your site may be serving cached pages to logged-in users--so you're seeing the logged-out cached version. There is a setting to change this behavior that you may want to change, then flush your cache.
