### ISSUE TITLE
No mobile cache in WP Supercache

### ISSUE THREAD

**Issue by ComboZombi** [Automattic/wp-super-cache#517]
Hello dear sirs! Today ive got a mobile version of my Avada website. This mobile version is entirely custom made and is activated through a js and css right under the "head". All mobile version templates and scripts are located in the root directory of my dedicated hosting. But for some reason WP Supercache does not serve supercached pages to mobile users. My theme responsive switch is OFF and my WP Supercache mobile support is ON. Could you please help me with this? I ll be happy to donate if a soultion is found! Thank you so much!

**Comment by kraftbj** [comment]
Howdy,

WP Super Cache captures built WordPress pages to save from the database work on each grab. I would suspect that the method used in your theme to bring in your templates is not one that hooks into the WordPress processes we're using.

Caching custom templates outside of a regular WordPress load is out of scope for WP Super Cache itself—may require a specific WP Super Cache plugin to be added to account for how that setup works and not something on our roadmap to develop.
