### ISSUE TITLE
Not Cache 404 Pages

### ISSUE THREAD

**Issue by anonprophet** [Automattic/wp-super-cache#518]
Hi, the cache works very well in home, archive, and single page..
but it doesnt work in 404 pages,

is there any setting to make it work on 404 page?

**Comment by donnchawp** [comment]
No, 404 pages are not cached by design and will never be cached. If you're getting enough 404 pages to be a problem you should be redirecting the user to the correct page.

**Comment by chrissound** [comment]
https://wordpress.org/support/topic/caching-of-404-pages/ 

"There aren’t options to force caching, but it’s possible with filter wpsupercache_404."
