### ISSUE TITLE
Notices on admin page from wp_cache_replace_line

### ISSUE THREAD

**Issue by mackensen** [Automattic/wp-super-cache#520]
Since upgrading from 1.5.3 to 1.5.9 we're seeing a bunch of notices from `wp_cache_replace_line` on the admin pages. Here's an example:

```
Warning: fopen(../public/wp-content/254072580.php): failed to open stream: Permission denied in ../public/wp-content/plugins/wp-super-cache/wp-cache-phase2.php on line 1070

Notice: wp_cache_replace_line: Error - could not write to ../public/wp-content/254072580.php in ../public/wp-content/plugins/wp-super-cache/wp-cache-phase2.php on line 1072
```

I'm not sure what the plugin is even trying to do here. `wp-cache-config.php` is writable, and so is `cache/`, but `wp-content` isn't generally writable by the web server and never was.

**Comment by arendvw** [comment]
See also the discussion at #535 
Wp super cache assumes the WP_CONTENT_DIR is world writable, changes to the config file are first written to a temporary file, in WP_CONTENT_DIR
