### ISSUE TITLE
Why vary on cookie?

### ISSUE THREAD

**Issue by ahmed-sigmalux** [Automattic/wp-super-cache#522]
WP Super Cache is hardcoded to add this header:

`header( "Vary: Accept-Encoding, Cookie" );`

In general, varying on cookies is bad practice, so why does WP Super Cache add vary on cookie?

Currently I'm removing the header and only varying on Accept-Encoding, but I'd like to know if there's some super secret and good reason for WP Super Cache to vary on cookies.

**Comment by marcotini** [comment]
I noticed that too. It's wrong because it's create double option on Vary and nginx create one too.

**Comment by donnchawp** [comment]
The plugin can cache pages for logged in users and those users are identified by cookie. If you remove "cookie" from there I think you may see odd things happen in proxied connections as a proxy/caching server might cache a private page.

But if you can test it and provide evidence that it's not needed it can be removed.

**Comment by donnchawp** [comment]
Unfortunately I don't have a host running Nginx to test on. Can you tell Nginx not to send that Vary header? A [comment here](https://github.com/wagtail/wagtail/issues/1111) says how to do it.

Or you could test if the Vary header has already been sent by Nginx using the PHP headers_list() command, but you'll need to edit WP Super Cache code to do that. Line [161 of wp-cache-phase2.php](https://github.com/Automattic/wp-super-cache/blob/71b92a6ce57a7f73971bc8b80ecb1df527ec61ec/wp-cache-phase2.php#L161) is probably where you want to add that test.

Do you know why Nginx adds the Vary: Cookie header? Is it for caching the web server does?

**Comment by marcotini** [comment]
Nginx doesn’t add Cookie, but Accept-Encoding. 
> Can you tell Nginx not to send that Vary header? A comment here says how to do it.
> 

Yes I can, but the Accept-Encoding? Who show it?

**Comment by donnchawp** [comment]
Check out #555 which lets you change that header by defining the constant WPSC_VARY_HEADER in your wp-config.php. It should have the header part after "Vary:".
