### ISSUE TITLE
Is it possible to require a certain file under current theme directory?

### ISSUE THREAD

**Issue by march1993** [Automattic/wp-super-cache#526]
For some circumstances, the theme generates different views based on cookie. The most straightforward method is to change the variable `$cache_path`. However, it can't be done with the theme self. So would it be possible to load a good-named file maybe `wp-super-cache-plugin.php` under current theme directory if it exists?

**Comment by donnchawp** [comment]
It's a good idea. I created a PR at #574 to define a specific directory outside of the wp-super-cache directory for plugins.

But this gives me the idea that the plugin system needs to be even more flexible. Allow other plugins/themes to define files that WP Super Cache should load. The plugin/theme runs a function with a filename, and that filename is saved to an array in the WP Super Cache configuration file.
