### ISSUE TITLE
wp_admin_replace_line assumes the WP_CONTENT_DIR is writable by the web-server

### ISSUE THREAD

**Issue by arendvw** [Automattic/wp-super-cache#535]
See wp-cache-phase2.php

https://github.com/Automattic/wp-super-cache/blob/cb662f57fff0a1dfaa8d2c699fd715177d47800c/wp-cache-phase2.php#L1071

This function assumes that it can write temporary files to the WP_CONTENT_DIR, which in many environment means that WP_CONTENT_DIR should be world or web-server writable. (With all severe security issues that would bring). 

It checks if the wp-cache-config file is writable, but not if the folder is writable. Thus failing silently, and not saving any changes to the wp-cache-config file.

Alternative could be to use the [tempnam](http://php.net/manual/en/function.tempnam.php) method of PHP to generate a temp file, by using e.g.

`$tmp_file = tempnam(sys_get_temp_dir(), 'wpcache');`

or to use the uploads or other known writable folder to write the temp file.

**Comment by stuartmaxwell** [comment]
I only just figured this out today after struggling with this for a while. I have to remember to change my wp-content directory permissions before editing the plugin.

**Comment by donnchawp** [comment]
I've added warnings when the wp-content directory or the config file is RO so at least you'll know why settings aren't being updated, but I'll reopen this as putting the temp file in sys_get_temp_dir() is probably the better way of creating that file. I need to test it properly before doing that however.

**Comment by donnchawp** [comment]
In #563 I fixed this by writing directly to the config file, as was done for a long time. This will avoid any problems with wp-content being read only.

**Comment by donnchawp** [comment]
In #563 I fixed this by writing directly to the config file, as was done for a long time. This will avoid any problems with wp-content being read only.
