### ISSUE TITLE
PHP 7.2 - Warning: Zend OPcache API is restricted by "restrict_api" configuration directive

### ISSUE THREAD

**Issue by celsoazevedo** [Automattic/wp-super-cache#536]
I've moved some of my WordPress sites to PHP 7.2. Now this warning is displayed on all WP Super Cache pages:

> Warning: Zend OPcache API is restricted by "restrict_api" configuration directive in /srv/users/c/apps/c/public/wp-content/plugins/wp-super-cache/wp-cache-phase2.php on line 1099

<img width="1236" alt="screen shot 2018-03-26 at 23 49 36" src="https://user-images.githubusercontent.com/4492221/37937232-b343719a-3150-11e8-9077-092301c6152f.png">

The cache itself seems to be working well, but the warning wasn't there with PHP 7.1. I'm using WordPress 4.9.2, PHP 7.2, and NGINX 1.13.9.

Someone else also [reported this issue](https://wordpress.org/support/topic/no-access-for-zend-opcache/) on the WordPress forums.

Let me know if you need more info.

Celso

**Comment by Rod-Gomes** [comment]
I own a hosting company and many of my clients complain about this error.

I can not remove the opcache restriction for obvious security reasons.
Could not you hide this alert?
