### ISSUE TITLE
Cache HTTP Headers with page content fails in some cases

### ISSUE THREAD

**Issue by thomasmery** [Automattic/wp-super-cache#539]
Hi there,

I had troubles making the discovery process for the WP Rest API work when caching was activated.

The _Link_  header containing the API base url could not be found.

It turns out that the plugin uses `apache_response_headers` if the function exists in `wp_cache_get_response_headers` method in `wp-cache-phase2.php`

after some tests it turns out that with _PHP 7.0 and above_ the function would return truncated Headers key in the array like: 

`Array ( [X-Powered-B] => PHP/7.0.28 )`

here notice the missing *y* at the end of _X-powered-by_ 

**Note:** tested on several servers with a bare call to the function and nothing else

in my case the _Link_ header would be _Lin_ and so it would of course not be cached as the plugin code relies on those keys to detect which Headers to keep by comparing them to the `known_headers` array it sets up

of course even cached a _Lin_ header would be useless ...

Commenting out the use of `wp_cache_get_response_headers` fixes the pb

I would open a PR for this but I could not find any indication of the `wp_cache_get_response_headers` behaviour with PHP 7 and would really appreciate some feedback on this and maybe some testing by others confirming or contradicting my findings

also even with using the fallback method - `headers_list` - one must be careful not to have 2 Headers with the same name as the code will only keep the last one in the list. This can happen if you have multiple _Link_ Headers for instance.

in my case I had trouble with the _shortlink_ header setup by WP that I had to remove using: 
`remove_action( 'template_redirect', 'wp_shortlink_header', 11);`

Thanks in advance for any help on this

**Comment by donnchawp** [comment]
I tried to replicate this and couldn't on an Apache server running PHP7. All the header keys are correct.

Unfortunately repeating headers will clobber earlier ones but the same would happen regardless. There can only be one canonical Link for example.

**Comment by thomasmery** [comment]
thanks,

mmm I'm confused as, as I have said, I tested on 2 servers with a bare call to _ apache_response_headers_ and got the same results

I'll try to investigate more and replicate on other environments

**Comment by stodorovic** [comment]
I just remembered that I've had similar issue with Apache 2.2 and  mod_fcgid. Which is version of apache? Which is PHP handler?

I've created better fallback for `apache_response_headers` in #496. Maybe it works better. You could test.

Some workaround which I've used is filter `wp_cache_meta` (It isn't perfect, but it could be solution until we find better). Example:

```php
add_filter( 'wp_cache_meta', 'xxxxxx_cache_link_header' );

function xxxxxx_cache_link_header( $wp_cache_meta ) {
        if ( isset( $GLOBALS[ 'wp_super_cache_query' ][ 'is_rest' ] ) ) {
                $api_root = get_rest_url();
                $wp_cache_meta[ 'headers' ][ 'Link' ] = '<' . esc_url_raw( $api_root ) . '>; rel="https://api.w.org/"';
        }

        return $wp_cache_meta;
}
```
I didn't test this code, but it's concept. You can use this filter to add custom headers for cached files. I've used it for X-Robots-Tag and it's worked. It's possible that `is_rest` isn't true in your case (it's true for default WP API). I don't know details and I'm waiting feedback from you..

**Comment by stodorovic** [comment]
Hi @thomasmery,

It's related to CGI SAPI. I see issue in PHP source code.

The code in [PHP 7.x](https://github.com/php/php-src/blob/PHP-7.2.11/sapi/cgi/cgi_main.c#L1737-L1739)
```c
do {
	len--;
} while (len != 0 && (h->header[len-1] == ' ' || h->header[len-1] == '\t'));
```
Issue is _do ... while_ loop because `len` will be decreased before condition. In [PHP 5.6](https://github.com/php/php-src/blob/PHP-5.6.38/sapi/cgi/cgi_main.c#L1679-L1681), I found correct code (_while_ loop):
```c
while (len > 0 && (h->header[len-1] == ' ' || h->header[len-1] == '\t')) {
	len--;
}
```
I'll report this as bug in PHP and I'll create new PR which uses only [headers_list](http://php.net/manual/en/function.headers-list.php) because this function works in my tests.

**Comment by stodorovic** [comment]
@thomasmery I've reported it as [PHP bug](https://bugs.php.net/bug.php?id=76859) and I've created #618 which uses only headers_list which fixes this issue. Could you test #618?

**Comment by stodorovic** [comment]
@thomasmery I've reported it as [PHP bug](https://bugs.php.net/bug.php?id=76954) and I've created #618 which uses only headers_list which fixes this issue. Could you test #618?
