### ISSUE TITLE
Misc Settings not saving

### ISSUE THREAD

**Issue by 0sm3l** [Automattic/wp-super-cache#550]
I'm trying to enable the "recommended" settings under advanced. I hit save, the page loads again with all the checks as if everything is fine but as soon as I reload the page all the settings are back to default. (1.6.0 / Multisite / WP 4.9.5 )

**Comment by kellymears** [comment]
Same

**Comment by donnchawp** [comment]
I can't replicate this. Did it happen in earlier versions of the plugin? Can you check if wp-content/wp-cache-config.php or the wp-content directory is owned by a user the webserver can update?

**Comment by donnchawp** [comment]
I think wp-content was probably RO so the plugin couldn't create a temp file in there to update the config file. I added warnings to the plugin when it can't update the config file but I'm going to look at other ways of updating it too.

**Comment by kellymears** [comment]
I can say for my part that wp-content is owned by www-data and all other plugins and core functionalities can write to that dir. This is a new issue. 

Thank you for adding the notice! 

I'll try to remember to provide error logs in the future but I believe it may have something to do with my usage of Amazon's Elastic File System which I mount to wp-content. I'm simplifying this architecture right now by nixing the EFS and Load Balancer (WP Super Cache is so good anyway, who needs to scale?) in hopes of finding resolution to this and other strange issues. 

Will take a snapshot before I kill the old instance.
