### ISSUE TITLE
Erroneous "Rewrite rules must be updated" notice that never goes away

### ISSUE THREAD

**Issue by zytzagoo** [Automattic/wp-super-cache#556]
It keeps saying:

The rewrite rules required by this plugin have changed or are missing. Scroll down the Advanced Settings page and click the **Update Mod_Rewrite Rules** button.

Clicking the button doesn't help (even though rewrite rules are updated/changed).

This is caused by https://github.com/Automattic/wp-super-cache/commit/6943fe9ea8fcb027aba37301d0ac65f99ba14ade#diff-d5e23b1d94909d6b8f2281f18d119027R377 -- that condition looks like it should be inverted.

**Comment by donnchawp** [comment]
Good catch! This only happens on multisite installs when viewing the advanced settings page on the main site.

**Comment by zytzagoo** [comment]
It was happening for me on single-site installs, whenever visiting the settings page.
