### ISSUE TITLE
Delete Cache redirection not working

### ISSUE THREAD

**Issue by bozzmedia** [Automattic/wp-super-cache#558]
Have had this issue over the last couple of years with this plugin, still remains a problem in the latest version.

To reproduce:

In the WP admin, click 'Delete Cache' while on a settings page, edit page, edit post, etc.

You are sent back to the main dashboard instead of the same page (ideally the cache is deleted and you are returned to the same page you are on).

The URL that is generated looks like the following. This one is generated from the frontend, click Delete cache in the toolbar. It should return me to the same frontend page after cache is cleared.

https://domainredacted.com/wp-admin/index.php?action=delcachepage&path=%2F2018%2F05%2F16%2Fpage-slug-281379&_wpnonce=e871d66275

**Comment by stodorovic** [comment]
Thank you for reporting this issue.

I’ve been able to reproduce the issue. It's possible in case when cache directory doesn't exist or nonce is expired. I just created #578 which should fix it.
