### ISSUE TITLE
WP-CLI causes infinite amount of semaphores via sem_get(NULL)

### ISSUE THREAD

**Issue by Crusse** [Automattic/wp-super-cache#569]
We have a cron job that periodically calls `wp-cli`.

When `wp_cache_mutex_init()` runs, it seems to call `sem_get()` with a `$sem_id` of `NULL`. A semaphore is created no matter what the value of `$wp_cache_mutex_disabled` is in `wp-content/wp-cache-config.php`.

This ends up eventually creating an "infinite" amount of semaphores (as shown by `ipcs -s`) after `wp-cli` has run multiple times, up to the system semaphore limits as given by `ipcs -l`.

This problem of infinite semaphores doesn't happen when WP is bootstrapped in the usual way, via an HTTP request.

```
wp-cli --version
WP-CLI 1.5.1
```

```
Plugin Name: WP Super Cache
Version: 1.6.2
```

http://php.net/manual/en/function.sem-get.php#119114

A quick-n-dirty fix is to set `define('WPSC_DISABLE_LOCKING', true)` in wp-config.php.

**Comment by donnchawp** [comment]
Can you debug the wp_cache_mutex_init() function please? The $wp_cache_mutex_disabled check in that function should stop sem_get() being called. Is there any chance the wp-cache-config.php file isn't loaded?

**Comment by stodorovic** [comment]
It's similar issue as #498. You can see more details in  #440 and #499 

I just created #576 which should fix it. Could you test it?

PS: Caching should be disabled for all backend request (includes wp-cli) - https://github.com/Automattic/wp-super-cache/blob/1.6.2/wp-cache-phase2.php#L1168-L1171 I'm not sure which is value of `$cache_enabled`, but I think that isn't root of cause.

**Comment by Crusse** [comment]
I confirm that #576 fixes the issue: an additional semaphore isn't created anymore each time WP-CLI is run on a WP multisite installation.

## Before having applied https://github.com/Automattic/wp-super-cache/pull/576/commits/e0662f591c5bea5ebcdb216775cf61c42990cb77:

```
root@b21126576c2c:/var/www/default/public# wp --allow-root eval 'echo "test" . PHP_EOL;' && ipcs -s
test

------ Semaphore Arrays --------
key        semid      owner      perms      nsems
0x00000000 131072     www-data   600        1
0x00000000 163841     www-data   600        1
0x00000000 196610     www-data   600        1
0x00000000 229379     root       666        3

root@b21126576c2c:/var/www/default/public# wp --allow-root eval 'echo "test" . PHP_EOL;' && ipcs -s
test

------ Semaphore Arrays --------
key        semid      owner      perms      nsems
0x00000000 131072     www-data   600        1
0x00000000 163841     www-data   600        1
0x00000000 196610     www-data   600        1
0x00000000 229379     root       666        3
0x00000000 262148     root       666        3

root@b21126576c2c:/var/www/default/public# wp --allow-root eval 'echo "test" . PHP_EOL;' && ipcs -s
test

------ Semaphore Arrays --------
key        semid      owner      perms      nsems
0x00000000 131072     www-data   600        1
0x00000000 163841     www-data   600        1
0x00000000 196610     www-data   600        1
0x00000000 229379     root       666        3
0x00000000 262148     root       666        3
0x00000000 294917     root       666        3
```

## After having applied https://github.com/Automattic/wp-super-cache/pull/576/commits/e0662f591c5bea5ebcdb216775cf61c42990cb77:

```
root@b21126576c2c:/var/www/default/public# wp --allow-root eval 'echo "test" . PHP_EOL;' && ipcs -s
test

------ Semaphore Arrays --------
key        semid      owner      perms      nsems
0x00000000 131072     www-data   600        1
0x00000000 163841     www-data   600        1
0x00000000 196610     www-data   600        1
0x00000000 229379     root       666        3
0x00000000 262148     root       666        3
0x00000000 294917     root       666        3

root@b21126576c2c:/var/www/default/public# wp --allow-root eval 'echo "test" . PHP_EOL;' && ipcs -s
test

------ Semaphore Arrays --------
key        semid      owner      perms      nsems
0x00000000 131072     www-data   600        1
0x00000000 163841     www-data   600        1
0x00000000 196610     www-data   600        1
0x00000000 229379     root       666        3
0x00000000 262148     root       666        3
0x00000000 294917     root       666        3

root@b21126576c2c:/var/www/default/public# wp --allow-root eval 'echo "test" . PHP_EOL;' && ipcs -s
test

------ Semaphore Arrays --------
key        semid      owner      perms      nsems
0x00000000 131072     www-data   600        1
0x00000000 163841     www-data   600        1
0x00000000 196610     www-data   600        1
0x00000000 229379     root       666        3
0x00000000 262148     root       666        3
0x00000000 294917     root       666        3
```

**Comment by donnchawp** [comment]
Thanks @stodorovic for fixing that, and to @Crusse for the extensive debugging!
