### ISSUE TITLE
wp_cache_get_cookies_values() is greedy

### ISSUE THREAD

**Issue by mackensen** [Automattic/wp-super-cache#58]
I'm administering multiple wordpress multisite domains each of which has WP Super Cache activated. It looks as though `wp_cache_get_cookies_values()` checks for the existence of a `^wordpress_logged_in_` cookie but doesn't verify that the user is logged in for that particular site. The effect is that if you're logged into any WordPress site, anywhere, you're treated as a logged-in user everywhere and don't get served the cached page.

**Comment by kraftbj** [comment]
We'll kick this one around a bit. On a traditional multisite, there is one shared cookie for the entire multisite, so if you are logged in somewhere you are logged in everywhere. 

Are you using Domain Mapping? If so, are you using Donncha's plugin or a different one? If using the Domain Mapping plugin, do you have the remote login setting checked? (wp-admin/network, settings->domain mapping)

**Comment by mackensen** [comment]
Thanks! We're not using the Domain Mapping plugin. We have three separate multisites where we're using Super Cache. One of them is a wildcard subdomain with custom names so we're setting both `COOKIE_DOMAIN` and `COOKIEHASH` in wp-config to constrain logins to that multisite. The other two are a conventional subdomain and subsite and we haven't configured anything additional. To clarify, the issue is that if I'm logged into any one of these three multisite environments I see logged-in user behavior from all of them. This includes our staging and development environments.

**Comment by donnchawp** [comment]
@mackensen - we already use LOGGED_IN_COOKIE which is defined in the same function as COOKIEHASH and uses COOKIEHASH in it.

Are you finding that "LOGGED_IN_COOKIE" isn't defined?

**Comment by mackensen** [comment]
@donnchawp Sorry about the delay. Yes, that's the behavior I'm seeing. LOGGED_IN_COOKIE is undefined.

**Comment by donnchawp** [comment]
I don't expect a reply, as this ticket has lingered way too long, but I presume COOKIEHASH and COOKIE_DOMAIN that you define in wp-config.php are unique to each site? Are you using the domain mapping plugin to map hostnames off the same domain?

I still don't understand why LOGGED_IN_COOKIE could *not* be defined as it's defined in wp_cookie_constants() so maybe a developer has hacked some core files to stop that happening.

I'm going to merge the patch however. The core code uses COOKIEHASH in defining those cookie names and the plugin should too. For the vast majority of users there won't be any change.
