### ISSUE TITLE
$cache_enabled is inconsistent with WP-CLI in multisite vs single site

### ISSUE THREAD

**Issue by Crusse** [Automattic/wp-super-cache#586]
With a `wp-cache-config.php` like this:

```
$cache_enabled = true; //Added by WP-Cache Manager
$super_cache_enabled = true; //Added by WP-Cache Manager
```

When running WP-CLI (e.g. `wp eval 'echo "hi" . PHP_EOL;'`):

- **Single site**: `$cache_enabled` is **`false`** in [wp-cache.php](https://github.com/Automattic/wp-super-cache/blob/1.6.3/wp-cache.php#L80) and [wp_cache_postload()](https://github.com/Automattic/wp-super-cache/blob/1.6.3/wp-cache-phase2.php#L301-L314)
- **Multisite**: `$cache_enabled` is **`true`** in [wp-cache.php](https://github.com/Automattic/wp-super-cache/blob/1.6.3/wp-cache.php#L80) and [wp_cache_postload()](https://github.com/Automattic/wp-super-cache/blob/1.6.3/wp-cache-phase2.php#L301-L314)

This is because [plugins/wp-super-cache/wp-cache-base.php](https://github.com/Automattic/wp-super-cache/blob/master/wp-cache-base.php#L2-L4) sets `$cached_enabled = false` only when `$_SERVER['HTTP_HOST']` is not set, and because WP-CLI spoofs `$_SERVER['HTTP_HOST']` only when `DOMAIN_CURRENT_SITE` is defined (and it's usually only defined in multisites' `wp-config.php`):

https://github.com/wp-cli/wp-cli/blob/c988a2c58c2a58123f5e143eb02e99beae92193a/php/WP_CLI/Runner.php#L1243
and
https://github.com/wp-cli/wp-cli/blob/master/php/class-wp-cli.php#L99

When running WP-CLI in multisite, the stack trace is:

```
#0 /var/www/default/wp-content/plugins/wp-super-cache/wp-cache-phase2.php(312): wp_cache_phase2()
#1 /var/www/default/wordpress/wp-settings.php(318): wp_cache_postload()
#2 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(1182): require('/var/www/defaul...')
#3 phar:///usr/local/bin/wp/vendor/wp-cli/eval-command/src/Eval_Command.php(34): WP_CLI\Runner->load_wordpress()
```

In single site, [wp_cache_postload() will instead terminate early](https://github.com/Automattic/wp-super-cache/blob/1.6.3/wp-cache-phase2.php#L304) due to `$cache_enabled` being `false`, and won't even call `wp_cache_phase2()`.

Therefore, when running WP-CLI, [whatever is run before](https://github.com/Automattic/wp-super-cache/blob/1.6.3/wp-cache-phase2.php#L1154-L1180) the [call to `wpsc_is_backend()`](https://github.com/Automattic/wp-super-cache/blob/1.6.3/wp-cache-phase2.php#L1181-L1183), only gets run in multisite, not single site.

This might not be related to any functional bug at the moment (Super Cache 1.6.3), but I felt the need to mention this, as this inconsistency might cause problems in the future.

--------------

_This is a continuation of the discussion in https://github.com/Automattic/wp-super-cache/issues/569#issuecomment-408453078._

**Comment by Crusse** [comment]
The commit in which `$cache_enabled = false` was added to `wp-cache-base.php`: https://github.com/Automattic/wp-super-cache/commit/57adc337390d95f05eb8051bc2ef0eafe176cab8#diff-74cc9346947dac9fdecef0717719d945

Ref: https://wordpress.org/support/topic/php-notice-undefined-index-http_host-from-wp-cli/

**Comment by stodorovic** [comment]
There are few issue related to WP-CLI and I'm thinking to create new issue which links all of them. I want to improve php-cli compatibility :smile: if you want to help us with testing.

WP-CLI populates `$_SERVER['HTTP_HOST']` if `--url` [parameter](https://make.wordpress.org/cli/handbook/config/) exists. Example:

```
$ wp --url='http://example.com' eval 'var_dump( $GLOBALS["cache_enabled"] );'
phar:///...: eval()'d code:1:
bool(true)
$ wp eval 'var_dump( $GLOBALS["cache_enabled"] );'
phar:///...: eval()'d code:1:
bool(false)
```
Regarding that WP-CLI doesn't load `advanced-cache.php` and `wp-cache-base.php` is loaded from `wp-cache.php` then it's possible to use `get_option( 'home' )` and set correct value for `$WPSC_HTTP_HOST` (and avoid set `$cache_enabled` to false). I just created PR #587 which fixes this issue.
