### ISSUE TITLE
Directly cached files missing in last version

### ISSUE THREAD

**Issue by marcomarsala** [Automattic/wp-super-cache#619]
Feature missing in latest version.

**Comment by stodorovic** [comment]
By quick checking, it seems that "this feature" still exists in `wp-cache-config.php` and admin page. It's possible that some changes in latest versions (I'm not sure that's related only to 1.6.4)  prevent creation of cache files. I didn't test.
@marcomarsala Could you send more details?

**Comment by marcomarsala** [comment]
The feature is missing in the UI


________________________________
Da: Saša Todorović <notifications@github.com>
Inviato: martedì, ottobre 2, 2018 3:07 PM
A: Automattic/wp-super-cache
Cc: Marco Marsala; Mention
Oggetto: Re: [Automattic/wp-super-cache] Directly cached files missing in last version (#619)


By quick checking, it seems that "this feature" still exists in wp-cache-config.php and admin page. It's possible that some changes in latest versions (I'm not sure that's related only to 1.6.4) prevent creation of cache files. I didn't test.
@marcomarsala<https://github.com/marcomarsala> Could you send more details?

**Comment by stodorovic** [comment]
I've created #622 (it fixes UI, but) it seems that we need more changes related to "direct pages".
