### ISSUE TITLE
In multisite for subdomain, WP Super Cache Preload not working!

### ISSUE THREAD

**Issue by shangdev** [Automattic/wp-super-cache#624]
This is some error message: 

> Warning! wp-cron.php not found!
Unfortunately, WordPress cannot find the file wp-cron.php. This script is required for the correct operation of garbage collection by this plugin, WordPress scheduled posts as well as other critical activities.
Please see entry 16 in the <a href="%s">Troubleshooting section</a> of the readme.txt

It seems that wp-cron has some problems. Is this a bug in subdomain multisite?

![image](https://user-images.githubusercontent.com/15621520/46857094-bc74db00-ce3a-11e8-9380-8d9881443606.png)

**Comment by shangdev** [comment]
This is log:

> 07:57:28 1684 /wp-admin/admin-ajax.php Setting up WordPress actions
07:57:28 1684 /wp-admin/admin-ajax.php Not caching wp-admin requests.
07:57:31 26583 /wp-admin/network/settings.php?page=wpsupercache&tab=easy wp_cache_get_cookies_values: /^wp-postpass_|^comment_author_|^wordpress_logged_in_/ Cookie detected: wordpress_logged_in_2a35dac80f8d2dba9071cc5f31db9e70
07:57:31 26583 /wp-admin/network/settings.php?page=wpsupercache&tab=easy wp_cache_get_cookies_values: return: a31be5a70e30d4cb12886244aa618255
07:57:31 26583 /wp-admin/network/settings.php?page=wpsupercache&tab=easy Caching disabled for logged in users on settings page.
07:57:32 26583 /wp-admin/network/settings.php?page=wpsupercache&tab=easy wp_cache_get_cookies_values: cached: a31be5a70e30d4cb12886244aa618255
07:57:32 26583 /wp-admin/network/settings.php?page=wpsupercache&tab=easy wp_cache_check_mobile: dev.trueniu.com80a31be5a70e30d4cb12886244aa618255
07:57:32 26583 /wp-admin/network/settings.php?page=wpsupercache&tab=easy In WP Cache Phase 2
07:57:32 26583 /wp-admin/network/settings.php?page=wpsupercache&tab=easy Setting up WordPress actions
07:57:32 26583 /wp-admin/network/settings.php?page=wpsupercache&tab=easy Not caching wp-admin requests.
07:57:34 26583 /wp-admin/network/settings.php?page=wpsupercache&tab=easy maybe_stop_gc: GC flag not found. GC will go ahead..
07:57:44 8086 /wp-admin/network/plugins.php wp_cache_get_cookies_values: /^wp-postpass_|^comment_author_|^wordpress_logged_in_/ Cookie detected: wordpress_logged_in_2a35dac80f8d2dba9071cc5f31db9e70
07:57:44 8086 /wp-admin/network/plugins.php wp_cache_get_cookies_values: return: a31be5a70e30d4cb12886244aa618255
07:57:44 8086 /wp-admin/network/plugins.php Caching disabled for logged in users on settings page.
07:57:44 8086 /wp-admin/network/plugins.php wp_cache_get_cookies_values: cached: a31be5a70e30d4cb12886244aa618255
07:57:44 8086 /wp-admin/network/plugins.php wp_cache_check_mobile: dev.trueniu.com80a31be5a70e30d4cb12886244aa618255
07:57:44 8086 /wp-admin/network/plugins.php In WP Cache Phase 2
07:57:44 8086 /wp-admin/network/plugins.php Setting up WordPress actions
07:57:44 8086 /wp-admin/network/plugins.php Not caching wp-admin requests.
07:57:50 7550 /wp-admin/ wp_cache_get_cookies_values: /^wp-postpass_|^comment_author_|^wordpress_logged_in_/ Cookie detected: wordpress_logged_in_2a35dac80f8d2dba9071cc5f31db9e70
07:57:50 7550 /wp-admin/ wp_cache_get_cookies_values: return: a31be5a70e30d4cb12886244aa618255
07:57:50 7550 /wp-admin/ Caching disabled for logged in users on settings page.
07:57:50 7550 /wp-admin/ wp_cache_get_cookies_values: cached: a31be5a70e30d4cb12886244aa618255
07:57:50 7550 /wp-admin/ wp_cache_check_mobile: dev.trueniu.com80a31be5a70e30d4cb12886244aa618255
07:57:50 7550 /wp-admin/ In WP Cache Phase 2
07:57:50 7550 /wp-admin/ Setting up WordPress actions
07:57:50 7550 /wp-admin/ Not caching wp-admin requests.
07:57:58 6655 /wp-admin/options-general.php?page=wpsupercache wp_cache_get_cookies_values: /^wp-postpass_|^comment_author_|^wordpress_logged_in_/ Cookie detected: wordpress_logged_in_2a35dac80f8d2dba9071cc5f31db9e70
07:57:58 6655 /wp-admin/options-general.php?page=wpsupercache wp_cache_get_cookies_values: return: a31be5a70e30d4cb12886244aa618255
07:57:58 6655 /wp-admin/options-general.php?page=wpsupercache Caching disabled for logged in users on settings page.
07:57:58 6655 /wp-admin/options-general.php?page=wpsupercache wp_cache_get_cookies_values: cached: a31be5a70e30d4cb12886244aa618255
07:57:58 6655 /wp-admin/options-general.php?page=wpsupercache wp_cache_check_mobile: dev.trueniu.com80a31be5a70e30d4cb12886244aa618255
07:57:58 6655 /wp-admin/options-general.php?page=wpsupercache In WP Cache Phase 2
07:57:58 6655 /wp-admin/options-general.php?page=wpsupercache Setting up WordPress actions
07:57:58 6655 /wp-admin/options-general.php?page=wpsupercache Not caching wp-admin requests.
07:58:00 6655 /wp-admin/options-general.php?page=wpsupercache maybe_stop_gc: GC flag not found. GC will go ahead..
07:58:02 1685 /wp-admin/options-general.php?page=wpsupercache&tab=preload wp_cache_get_cookies_values: /^wp-postpass_|^comment_author_|^wordpress_logged_in_/ Cookie detected: wordpress_logged_in_2a35dac80f8d2dba9071cc5f31db9e70
07:58:02 1685 /wp-admin/options-general.php?page=wpsupercache&tab=preload wp_cache_get_cookies_values: return: a31be5a70e30d4cb12886244aa618255
07:58:02 1685 /wp-admin/options-general.php?page=wpsupercache&tab=preload Caching disabled for logged in users on settings page.
07:58:02 1685 /wp-admin/options-general.php?page=wpsupercache&tab=preload wp_cache_get_cookies_values: cached: a31be5a70e30d4cb12886244aa618255
07:58:02 1685 /wp-admin/options-general.php?page=wpsupercache&tab=preload wp_cache_check_mobile: dev.trueniu.com80a31be5a70e30d4cb12886244aa618255
07:58:02 1685 /wp-admin/options-general.php?page=wpsupercache&tab=preload In WP Cache Phase 2
07:58:02 1685 /wp-admin/options-general.php?page=wpsupercache&tab=preload Setting up WordPress actions
07:58:02 1685 /wp-admin/options-general.php?page=wpsupercache&tab=preload Not caching wp-admin requests.
07:58:04 1685 /wp-admin/options-general.php?page=wpsupercache&tab=preload maybe_stop_gc: GC flag not found. GC will go ahead..
07:58:15 1680 /wp-admin/network/plugins.php?action=deactivate&plugin=trueniu-init%2Ftrueniu-init.php&plugin_status=all&paged=1&s&_wpnonce=65caed44a1 wp_cache_get_cookies_values: /^wp-postpass_|^comment_author_|^wordpress_logged_in_/ Cookie detected: wordpress_logged_in_2a35dac80f8d2dba9071cc5f31db9e70
07:58:15 1680 /wp-admin/network/plugins.php?action=deactivate&plugin=trueniu-init%2Ftrueniu-init.php&plugin_status=all&paged=1&s&_wpnonce=65caed44a1 wp_cache_get_cookies_values: return: a31be5a70e30d4cb12886244aa618255
07:58:15 1680 /wp-admin/network/plugins.php?action=deactivate&plugin=trueniu-init%2Ftrueniu-init.php&plugin_status=all&paged=1&s&_wpnonce=65caed44a1 Caching disabled for logged in users on settings page.
07:58:16 1680 /wp-admin/network/plugins.php?action=deactivate&plugin=trueniu-init%2Ftrueniu-init.php&plugin_status=all&paged=1&s&_wpnonce=65caed44a1 wp_cache_get_cookies_values: cached: a31be5a70e30d4cb12886244aa618255
07:58:16 1680 /wp-admin/network/plugins.php?action=deactivate&plugin=trueniu-init%2Ftrueniu-init.php&plugin_status=all&paged=1&s&_wpnonce=65caed44a1 wp_cache_check_mobile: dev.trueniu.com80a31be5a70e30d4cb12886244aa618255
07:58:16 1680 /wp-admin/network/plugins.php?action=deactivate&plugin=trueniu-init%2Ftrueniu-init.php&plugin_status=all&paged=1&s&_wpnonce=65caed44a1 In WP Cache Phase 2
07:58:16 1680 /wp-admin/network/plugins.php?action=deactivate&plugin=trueniu-init%2Ftrueniu-init.php&plugin_status=all&paged=1&s&_wpnonce=65caed44a1 Setting up WordPress actions
07:58:16 1680 /wp-admin/network/plugins.php?action=deactivate&plugin=trueniu-init%2Ftrueniu-init.php&plugin_status=all&paged=1&s&_wpnonce=65caed44a1 Not caching wp-admin requests.
07:58:18 1677 /wp-admin/network/plugins.php?deactivate=true&plugin_status=all&paged=1&s= wp_cache_get_cookies_values: /^wp-postpass_|^comment_author_|^wordpress_logged_in_/ Cookie detected: wordpress_logged_in_2a35dac80f8d2dba9071cc5f31db9e70
07:58:18 1677 /wp-admin/network/plugins.php?deactivate=true&plugin_status=all&paged=1&s= wp_cache_get_cookies_values: return: a31be5a70e30d4cb12886244aa618255
07:58:18 1677 /wp-admin/network/plugins.php?deactivate=true&plugin_status=all&paged=1&s= Caching disabled for logged in users on settings page.
07:58:18 1677 /wp-admin/network/plugins.php?deactivate=true&plugin_status=all&paged=1&s= wp_cache_get_cookies_values: cached: a31be5a70e30d4cb12886244aa618255
07:58:18 1677 /wp-admin/network/plugins.php?deactivate=true&plugin_status=all&paged=1&s= wp_cache_check_mobile: dev.trueniu.com80a31be5a70e30d4cb12886244aa618255
07:58:18 1677 /wp-admin/network/plugins.php?deactivate=true&plugin_status=all&paged=1&s= In WP Cache Phase 2
07:58:18 1677 /wp-admin/network/plugins.php?deactivate=true&plugin_status=all&paged=1&s= Setting up WordPress actions
07:58:18 1677 /wp-admin/network/plugins.php?deactivate=true&plugin_status=all&paged=1&s= Not caching wp-admin requests.
07:58:23 1674 /wp-admin/options-general.php?page=wpsupercache&tab=preload wp_cache_get_cookies_values: /^wp-postpass_|^comment_author_|^wordpress_logged_in_/ Cookie detected: wordpress_logged_in_2a35dac80f8d2dba9071cc5f31db9e70
07:58:23 1674 /wp-admin/options-general.php?page=wpsupercache&tab=preload wp_cache_get_cookies_values: return: a31be5a70e30d4cb12886244aa618255
07:58:23 1674 /wp-admin/options-general.php?page=wpsupercache&tab=preload Caching disabled for logged in users on settings page.
07:58:23 1674 /wp-admin/options-general.php?page=wpsupercache&tab=preload wp_cache_get_cookies_values: cached: a31be5a70e30d4cb12886244aa618255
07:58:23 1674 /wp-admin/options-general.php?page=wpsupercache&tab=preload wp_cache_check_mobile: dev.trueniu.com80a31be5a70e30d4cb12886244aa618255
07:58:23 1674 /wp-admin/options-general.php?page=wpsupercache&tab=preload In WP Cache Phase 2
07:58:23 1674 /wp-admin/options-general.php?page=wpsupercache&tab=preload Setting up WordPress actions
07:58:23 1674 /wp-admin/options-general.php?page=wpsupercache&tab=preload Not caching wp-admin requests.
07:58:25 1674 /wp-admin/options-general.php?page=wpsupercache&tab=preload maybe_stop_gc: GC flag not found. GC will go ahead..
07:58:28 1684 /wp-admin/admin-ajax.php wp_cache_get_cookies_values: /^wp-postpass_|^comment_author_|^wordpress_logged_in_/ Cookie detected: wordpress_logged_in_2a35dac80f8d2dba9071cc5f31db9e70
07:58:28 1684 /wp-admin/admin-ajax.php wp_cache_get_cookies_values: return: 194b7cd61c3c148893a41803f8699b90
07:58:28 1684 /wp-admin/admin-ajax.php Caching disabled for logged in users on settings page.
07:58:28 1684 /wp-admin/admin-ajax.php wp_cache_get_cookies_values: cached: 194b7cd61c3c148893a41803f8699b90
07:58:28 1684 /wp-admin/admin-ajax.php wp_cache_check_mobile: dev.sj-relays.com80194b7cd61c3c148893a41803f8699b90
07:58:28 1684 /wp-admin/admin-ajax.php In WP Cache Phase 2
07:58:28 1684 /wp-admin/admin-ajax.php Setting up WordPress actions
07:58:28 1684 /wp-admin/admin-ajax.php Not caching wp-admin requests.
07:58:28 26583 /wp-admin/options-general.php?page=wpsupercache&tab=preload wp_cache_get_cookies_values: /^wp-postpass_|^comment_author_|^wordpress_logged_in_/ Cookie detected: wordpress_logged_in_2a35dac80f8d2dba9071cc5f31db9e70
07:58:28 26583 /wp-admin/options-general.php?page=wpsupercache&tab=preload wp_cache_get_cookies_values: return: 194b7cd61c3c148893a41803f8699b90
07:58:28 26583 /wp-admin/options-general.php?page=wpsupercache&tab=preload Caching disabled for logged in users on settings page.
07:58:28 26583 /wp-admin/options-general.php?page=wpsupercache&tab=preload wp_cache_get_cookies_values: cached: 194b7cd61c3c148893a41803f8699b90
07:58:28 26583 /wp-admin/options-general.php?page=wpsupercache&tab=preload wp_cache_check_mobile: dev.sj-relays.com80194b7cd61c3c148893a41803f8699b90
07:58:28 26583 /wp-admin/options-general.php?page=wpsupercache&tab=preload In WP Cache Phase 2
07:58:28 26583 /wp-admin/options-general.php?page=wpsupercache&tab=preload Setting up WordPress actions
07:58:28 26583 /wp-admin/options-general.php?page=wpsupercache&tab=preload Not caching wp-admin requests.
07:58:30 26583 /wp-admin/options-general.php?page=wpsupercache&tab=preload maybe_stop_gc: GC flag not found. GC will go ahead..
07:58:32 8086 /wp-admin/options-general.php?page=wpsupercache&tab=preload wp_cache_get_cookies_values: /^wp-postpass_|^comment_author_|^wordpress_logged_in_/ Cookie detected: wordpress_logged_in_2a35dac80f8d2dba9071cc5f31db9e70
07:58:32 8086 /wp-admin/options-general.php?page=wpsupercache&tab=preload wp_cache_get_cookies_values: return: 194b7cd61c3c148893a41803f8699b90
07:58:32 8086 /wp-admin/options-general.php?page=wpsupercache&tab=preload Caching disabled for logged in users on settings page.
07:58:32 8086 /wp-admin/options-general.php?page=wpsupercache&tab=preload wp_cache_get_cookies_values: cached: 194b7cd61c3c148893a41803f8699b90
07:58:32 8086 /wp-admin/options-general.php?page=wpsupercache&tab=preload wp_cache_check_mobile: dev.sj-relays.com80194b7cd61c3c148893a41803f8699b90
07:58:32 8086 /wp-admin/options-general.php?page=wpsupercache&tab=preload In WP Cache Phase 2
07:58:32 8086 /wp-admin/options-general.php?page=wpsupercache&tab=preload Setting up WordPress actions
07:58:32 8086 /wp-admin/options-general.php?page=wpsupercache&tab=preload Not caching wp-admin requests.
07:58:34 8086 /wp-admin/options-general.php?page=wpsupercache&tab=preload maybe_stop_gc: GC flag not found. GC will go ahead..
07:58:38 7550 /wp-admin/options-general.php?page=wpsupercache&tab=preload wp_cache_get_cookies_values: /^wp-postpass_|^comment_author_|^wordpress_logged_in_/ Cookie detected: wordpress_logged_in_2a35dac80f8d2dba9071cc5f31db9e70
07:58:38 7550 /wp-admin/options-general.php?page=wpsupercache&tab=preload wp_cache_get_cookies_values: return: a31be5a70e30d4cb12886244aa618255
07:58:38 7550 /wp-admin/options-general.php?page=wpsupercache&tab=preload Caching disabled for logged in users on settings page.
07:58:38 7550 /wp-admin/options-general.php?page=wpsupercache&tab=preload wp_cache_get_cookies_values: cached: a31be5a70e30d4cb12886244aa618255
07:58:38 7550 /wp-admin/options-general.php?page=wpsupercache&tab=preload wp_cache_check_mobile: dev.trueniu.com80a31be5a70e30d4cb12886244aa618255
07:58:38 7550 /wp-admin/options-general.php?page=wpsupercache&tab=preload In WP Cache Phase 2
07:58:38 7550 /wp-admin/options-general.php?page=wpsupercache&tab=preload Setting up WordPress actions
07:58:38 7550 /wp-admin/options-general.php?page=wpsupercache&tab=preload Not caching wp-admin requests.
07:58:41 7550 /wp-admin/options-general.php?page=wpsupercache&tab=preload maybe_stop_gc: GC flag not found. GC will go ahead..
07:59:20 6655 /wp-admin/admin-ajax.php wp_cache_get_cookies_values: /^wp-postpass_|^comment_author_|^wordpress_logged_in_/ Cookie detected: wordpress_logged_in_2a35dac80f8d2dba9071cc5f31db9e70
07:59:20 6655 /wp-admin/admin-ajax.php wp_cache_get_cookies_values: return: a31be5a70e30d4cb12886244aa618255
07:59:20 6655 /wp-admin/admin-ajax.php Caching disabled for logged in users on settings page.
07:59:20 6655 /wp-admin/admin-ajax.php wp_cache_get_cookies_values: cached: a31be5a70e30d4cb12886244aa618255
07:59:20 6655 /wp-admin/admin-ajax.php wp_cache_check_mobile: dev.trueniu.com80a31be5a70e30d4cb12886244aa618255
07:59:20 6655 /wp-admin/admin-ajax.php In WP Cache Phase 2
07:59:20 6655 /wp-admin/admin-ajax.php Setting up WordPress actions
07:59:20 6655 /wp-admin/admin-ajax.php Not caching wp-admin requests.
07:59:35 23158 /wp-admin/admin-ajax.php wp_cache_get_cookies_values: /^wp-postpass_|^comment_author_|^wordpress_logged_in_/ Cookie detected: wordpress_logged_in_2a35dac80f8d2dba9071cc5f31db9e70
07:59:35 23158 /wp-admin/admin-ajax.php wp_cache_get_cookies_values: return: 194b7cd61c3c148893a41803f8699b90
07:59:35 23158 /wp-admin/admin-ajax.php Caching disabled for logged in users on settings page.
07:59:35 23158 /wp-admin/admin-ajax.php wp_cache_get_cookies_values: cached: 194b7cd61c3c148893a41803f8699b90
07:59:35 23158 /wp-admin/admin-ajax.php wp_cache_check_mobile: dev.sj-relays.com80194b7cd61c3c148893a41803f8699b90
07:59:35 23158 /wp-admin/admin-ajax.php In WP Cache Phase 2
07:59:35 23158 /wp-admin/admin-ajax.php Setting up WordPress actions
07:59:35 23158 /wp-admin/admin-ajax.php Not caching wp-admin requests.
07:59:37 1685 /wp-admin/options-general.php?page=wpsupercache&tab=preload wp_cache_get_cookies_values: /^wp-postpass_|^comment_author_|^wordpress_logged_in_/ Cookie detected: wordpress_logged_in_2a35dac80f8d2dba9071cc5f31db9e70
07:59:37 1685 /wp-admin/options-general.php?page=wpsupercache&tab=preload wp_cache_get_cookies_values: return: a31be5a70e30d4cb12886244aa618255
07:59:37 1685 /wp-admin/options-general.php?page=wpsupercache&tab=preload Caching disabled for logged in users on settings page.
07:59:37 1685 /wp-admin/options-general.php?page=wpsupercache&tab=preload wp_cache_get_cookies_values: cached: a31be5a70e30d4cb12886244aa618255
07:59:37 1685 /wp-admin/options-general.php?page=wpsupercache&tab=preload wp_cache_check_mobile: dev.trueniu.com80a31be5a70e30d4cb12886244aa618255
07:59:37 1685 /wp-admin/options-general.php?page=wpsupercache&tab=preload In WP Cache Phase 2
07:59:37 1685 /wp-admin/options-general.php?page=wpsupercache&tab=preload Setting up WordPress actions
07:59:37 1685 /wp-admin/options-general.php?page=wpsupercache&tab=preload Not caching wp-admin requests.
07:59:40 1685 /wp-admin/options-general.php?page=wpsupercache&tab=preload maybe_stop_gc: GC flag not found. GC will go ahead..
07:59:41 1680 /wp-admin/options-general.php?page=wpsupercache&tab=preload wp_cache_get_cookies_values: /^wp-postpass_|^comment_author_|^wordpress_logged_in_/ Cookie detected: wordpress_logged_in_2a35dac80f8d2dba9071cc5f31db9e70
07:59:41 1680 /wp-admin/options-general.php?page=wpsupercache&tab=preload wp_cache_get_cookies_values: return: 194b7cd61c3c148893a41803f8699b90
07:59:41 1680 /wp-admin/options-general.php?page=wpsupercache&tab=preload Caching disabled for logged in users on settings page.
07:59:42 1680 /wp-admin/options-general.php?page=wpsupercache&tab=preload wp_cache_get_cookies_values: cached: 194b7cd61c3c148893a41803f8699b90
07:59:42 1680 /wp-admin/options-general.php?page=wpsupercache&tab=preload wp_cache_check_mobile: dev.sj-relays.com80194b7cd61c3c148893a41803f8699b90
07:59:42 1680 /wp-admin/options-general.php?page=wpsupercache&tab=preload In WP Cache Phase 2
07:59:42 1680 /wp-admin/options-general.php?page=wpsupercache&tab=preload Setting up WordPress actions
07:59:42 1680 /wp-admin/options-general.php?page=wpsupercache&tab=preload Not caching wp-admin requests.
07:59:43 1680 /wp-admin/options-general.php?page=wpsupercache&tab=preload maybe_stop_gc: GC flag not found. GC will go ahead..
08:00:22 16337 /wp-admin/options-general.php?page=wpsupercache&tab=preload wp_cache_get_cookies_values: /^wp-postpass_|^comment_author_|^wordpress_logged_in_/ Cookie detected: wordpress_logged_in_2a35dac80f8d2dba9071cc5f31db9e70
08:00:22 16337 /wp-admin/options-general.php?page=wpsupercache&tab=preload wp_cache_get_cookies_values: return: a31be5a70e30d4cb12886244aa618255
08:00:22 16337 /wp-admin/options-general.php?page=wpsupercache&tab=preload Caching disabled for logged in users on settings page.
08:00:22 16337 /wp-admin/options-general.php?page=wpsupercache&tab=preload wp_cache_get_cookies_values: cached: a31be5a70e30d4cb12886244aa618255
08:00:22 16337 /wp-admin/options-general.php?page=wpsupercache&tab=preload wp_cache_check_mobile: dev.trueniu.com80a31be5a70e30d4cb12886244aa618255
08:00:22 16337 /wp-admin/options-general.php?page=wpsupercache&tab=preload In WP Cache Phase 2
08:00:22 16337 /wp-admin/options-general.php?page=wpsupercache&tab=preload Setting up WordPress actions
08:00:22 16337 /wp-admin/options-general.php?page=wpsupercache&tab=preload Not caching wp-admin requests.
08:00:25 16337 /wp-admin/options-general.php?page=wpsupercache&tab=preload maybe_stop_gc: GC flag not found. GC will go ahead..
08:00:26 1676 /wp-admin/options-general.php?page=wpsupercache&tab=preload wp_cache_get_cookies_values: /^wp-postpass_|^comment_author_|^wordpress_logged_in_/ Cookie detected: wordpress_logged_in_2a35dac80f8d2dba9071cc5f31db9e70
08:00:26 1676 /wp-admin/options-general.php?page=wpsupercache&tab=preload wp_cache_get_cookies_values: return: 194b7cd61c3c148893a41803f8699b90
08:00:26 1676 /wp-admin/options-general.php?page=wpsupercache&tab=preload Caching disabled for logged in users on settings page.
08:00:27 1676 /wp-admin/options-general.php?page=wpsupercache&tab=preload wp_cache_get_cookies_values: cached: 194b7cd61c3c148893a41803f8699b90
08:00:27 1676 /wp-admin/options-general.php?page=wpsupercache&tab=preload wp_cache_check_mobile: dev.sj-relays.com80194b7cd61c3c148893a41803f8699b90
08:00:27 1676 /wp-admin/options-general.php?page=wpsupercache&tab=preload In WP Cache Phase 2
08:00:27 1676 /wp-admin/options-general.php?page=wpsupercache&tab=preload Setting up WordPress actions
08:00:27 1676 /wp-admin/options-general.php?page=wpsupercache&tab=preload Not caching wp-admin requests.
08:00:28 1676 /wp-admin/options-general.php?page=wpsupercache&tab=preload maybe_stop_gc: GC flag not found. GC will go ahead..
08:00:30 26583 /wp-admin/options-general.php?page=wpsupercache&tab=preload wp_cache_get_cookies_values: /^wp-postpass_|^comment_author_|^wordpress_logged_in_/ Cookie detected: wordpress_logged_in_2a35dac80f8d2dba9071cc5f31db9e70
08:00:30 26583 /wp-admin/options-general.php?page=wpsupercache&tab=preload wp_cache_get_cookies_values: return: a31be5a70e30d4cb12886244aa618255
08:00:30 26583 /wp-admin/options-general.php?page=wpsupercache&tab=preload Caching disabled for logged in users on settings page.
08:00:31 26583 /wp-admin/options-general.php?page=wpsupercache&tab=preload wp_cache_get_cookies_values: cached: a31be5a70e30d4cb12886244aa618255
08:00:31 26583 /wp-admin/options-general.php?page=wpsupercache&tab=preload wp_cache_check_mobile: dev.trueniu.com80a31be5a70e30d4cb12886244aa618255
08:00:31 26583 /wp-admin/options-general.php?page=wpsupercache&tab=preload In WP Cache Phase 2
08:00:31 26583 /wp-admin/options-general.php?page=wpsupercache&tab=preload Setting up WordPress actions
08:00:31 26583 /wp-admin/options-general.php?page=wpsupercache&tab=preload Not caching wp-admin requests.
08:00:33 26583 /wp-admin/options-general.php?page=wpsupercache&tab=preload maybe_stop_gc: GC flag not found. GC will go ahead..

**Comment by stodorovic** [comment]
It seems that warning is related to dev site (maybe dev site is protected by password and cron doesn't work). Anyway, preload can't work without cron. You could trigger cron manually (by php script or via request from crontab). Did you try to make request from browser (site_url/wp-cron.php)?

Also, I've noticed some issues related to multisite and preload while I was trying to fix other issues. I'll try to make some PRs related to multisite/preload if you want to test them.

**Comment by shangdev** [comment]
@stodorovic 
I has make request from browser(site_url/wp-cron.php), But the problem still exists.

And I can go to test them. However, I do not have experience in this area and need a guide.
