### ISSUE TITLE
How to store cached files in S3?

### ISSUE THREAD

**Issue by epicfaace** [Automattic/wp-super-cache#626]
Hello, my WP site is deployed on elastic beanstalk so I wouldn't want my cached files to be stored locally on the server. How do I store them in S3 instead so that the cache is persistent?

**Comment by donnchawp** [comment]
I don't think this would be good for site performance, as your server would have to fetch the file from the s3 server and then serve it to the visitor, introducing a lot of lag.

If you want the s3 server to be some sort of transparent proxy between your server and visitors then you should try Cloudflare, as that's what they do.

**Comment by epicfaace** [comment]
Thanks!
