### ISSUE TITLE
Cache HTTP Headers: handle multiple fields with same name

### ISSUE THREAD

**Issue by Sysix** [Automattic/wp-super-cache#638]
Hello,

today I found a little "bug" when I used custom headers in my wordpress installation.
I set multiple `Link` headers and let it cache by WP Super Cache.

The Problem is, that only the last "Link" Header will show up, Because the Array-Entry is overriding the old Value. 

**Solution**  
Check if the Header-Name is already set and concat it with `, `.
I think the Line Fix should insert here:  
https://github.com/Automattic/wp-super-cache/blob/master/wp-cache-phase2.php#L2414

**Reference**
https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2

>>>
Multiple message-header fields with the same field-name MAY be present in a message if and only if the entire field-value for that header field is defined as a comma-separated list [i.e., #(values)]. It MUST be possible to combine the multiple header fields into one "field-name: field-value" pair, without changing the semantics of the message, by appending each subsequent field-value to the first, each separated by a comma. The order in which header fields with the same field-name are received is therefore significant to the interpretation of the combined field value, and thus a proxy MUST NOT change the order of these field values when a message is forwarded. 

>>>

**Comment by stodorovic** [comment]
I'm not sure that your approach is correct. We've already merged #618 which uses headers_list to retrieve all raw headers. It's first step, but additional changes should be done in function `wp_cache_get_response_headers`.

I'll check which I can do in next days.

**Comment by stodorovic** [comment]
@Sysix I've created #641 which will fix this issue.  Could you test this PR?
