### ISSUE TITLE
wp-cache-config.php corruption

### ISSUE THREAD

**Issue by DrLightman** [Automattic/wp-super-cache#646]
I've just finished sweating five shirts because of what happened.

I added an action to remove a cookie added by the plugin Cookie Notice. It adds a cookie named "cookie_noticed_accepted" with such an action upon `init` hook:

`do_action( 'wpsc_add_cookie', 'cookie_notice_accepted' );`

I wanted to try out without it and so I added an action at lower priority (11), to remove it:

`do_action('wpsc_delete_cookie', 'cookie_notice_accepted');`

The mess started. After some minutes cache was disabled, accessing wpsc settings fom dashboard gave server error 500, I didn't know where to look. I then looked at wp-cache-config.php via ftp, and it was really messy:

![corrupted wp cache config](https://i.ibb.co/QvXMwDQ/wpsc-config.png)

I applied the cookie_notice_accepted action on several sites and each of them had some different kind of corruption, with all those square characters (NULL bytes) in different positions. Some of them had the starting comments halfed so that whole config was commented out, some others had 2 closing php tags at the end:

some code ?> some code ?>

I never had this issue with wp-cache-config.php in, let's say, about 10 years, I had today after installing the wpsc_delete_cookie action.

**Comment by DrLightman** [comment]
Also, wouldn't be better to not use the closing php tag at all in wp-cache-config.php? It also has a line break after it, that is bad practice

**Comment by DrLightman** [comment]
I think here the problem stays also on the plugin Cookie Notice, since it does a settings save at every page load `init` hook. Too many concurrent file write can mess up the file pretty fast.

**Comment by donnchawp** [comment]
Good catch. I wonder if I should add an is_admin() check to the update settings functions to avoid these kind of problems. At least then it's only being updated in wp-admin.

The config file does have a trailing "?>" but that's because it was the convention to do that when it was created all those years ago. There isn't any trailing space in the file normally.

**Comment by stodorovic** [comment]
I was thinking that about possible solutions. Possible solution for "saving config file":

- Copy _$wpsc_cookies_ to _$wpsc_backup_cookies_ after loading config file.
- Remove _wp_cache_setting_ from _wpsc_add_cookie_ and _wpsc_delete_cookie_
- Register shutdown hook (or something else at the end) which calls _wp_cache_setting_ if _$wpsc_cookies !== $wpsc_backup_cookies_

From other side, I was thinking about "reset config file" if error is occurred. We could try to catch PHP error related to including config file and rename _wp-config.php_ to _wp-config-{timestamp}-backup.php_

@DrLightman You can unhook method (Cookie Notice) which adds cookies. You can try this:

```php
remove_action( 'init', array( $GLOBALS['cookie_notice'], 'add_wpsc_cookie' ) );
```

**Comment by donnchawp** [comment]
I suspect the value of $wpsc_cookies isn't changing at all on each load. I'd like to investigate how hard it would be to check if the value already set in the config file is unchanged. I'll open an issue to share my thoughts on that.
