### ISSUE TITLE
HTTP2 push header are getting removed from cached pages

### ISSUE THREAD

**Issue by rajeshsingh520** [Automattic/wp-super-cache#650]
i am using my pluign https://wordpress.org/plugins/http2-push-content/
this workes fine when used on its own, but then i activate Wp super cache
IT stops working,

It will add the http2 header on the very first request after activating the wp super cache (once page get cached) it won't send http2 push link in the header

If we clear cache and try it will send again but only once (as the page get cached it stops working)

**Comment by stodorovic** [comment]
There is [an issue](https://github.com/Automattic/wp-super-cache/issues/539) related to [apache_response_headers](http://php.net/manual/en/function.apache-response-headers.php) and [same topic](https://wordpress.org/support/topic/is-there-option-to-use-http2-push-with-wp-super-cache/) on support forum.

Which PHP version you have installed on your server? Did you enable option "Cache HTTP headers with page content" ?

**Comment by rajeshsingh520** [comment]
Thanks, this option was not enabled **Cache HTTP headers with page content** thats why it was not doing the push now it is working

Now I will check if there is such setting in the W3 total cache as well, because it is not working in there as well, But over there W3 total cache is recording those link in the htaccess
