### ISSUE TITLE
Need help with  wp_cache_ob_callback_filter

### ISSUE THREAD

**Issue by Key7i** [Automattic/wp-super-cache#663]
Hello,

I'm working on a plugin which take the final html output with `ob_start();` and replace empty alt tags for all images. It works fine except that wp super cache no longer works. Please check stakcoverflow topic on this.

https://stackoverflow.com/questions/772510/wordpress-filter-to-modify-final-html-output

It also have a solution for wp-super-cache to fix this issue. Which mentioned to use this filter.
https://stackoverflow.com/a/51171913/3465265

The problem is that its not working for me and i would really appreciate if someone can help me how to use this filter properly, so my plugin can replace alt tags first and then wp-super-cache create cache files.

Here is my code inside twentyseventeen function.php file.

```
ob_start();

add_action('shutdown', function() {
    $final = '';

    // We'll need to get the number of ob levels we're in, so that we can iterate over each, collecting
    // that buffer's output into the final output.
    $levels = ob_get_level();

    for ($i = 0; $i < $levels; $i++) {
        $final .= ob_get_clean();
    }

    // Apply any filters to the final output
    echo apply_filters('wp_cache_ob_callback_filter', $final);
}, 0);

add_filter('wp_cache_ob_callback_filter', function($output) {
    //this is where changes should be made

    $pattern1 ='~(<img.*? alt=")("[^>]*>)~i'; // alt empty
    $alt_keyword = "BUBBLE";
    $replace_fkw = '$1'. $alt_keyword .'$2';

    return $content = preg_replace($pattern1, $replace_fkw, $output);
});
```

Thanks

**Comment by stodorovic** [comment]
You should avoid mixing shutdown action and wp_cache_ob_callback_filter. I didn't test, but I expect side effects with this code.

You have two options:

- Use only wp_cache_ob_callback_filter:
```php
add_filter( 'wp_cache_ob_callback_filter', function( $output ) {

	// Your code

	return $output;
} );
```
- Use  [output_callback](https://www.php.net/manual/en/function.ob-start.php)k function:
```php
add_action( 'template_redirect', function() {
	ob_start(  'my_ob_handler'  );
} );

function my_ob_handler( $output ) {

	// Your code

	return $output;
}
```

**Comment by Key7i** [comment]
Thank you brother for the help. You're right.. Shutdown action was causing issue..
