### ISSUE TITLE
enhance log readabilty

### ISSUE THREAD

**Issue by roebert** [Automattic/wp-super-cache#68]
please add newlines to the logging, so the log file is better readable

**Comment by jom** [comment]
It has been using `\n` since d5ccc93fe78e46be6fa948a30070b2a9d851f0dc. For a while it was using `\n\r` (0d392b07b71cbf21bb5ac71e6d52317f3fab2cc3). In 7902634de526f5a024d121f6b7de50034cc0527f (#371; v1.5.6) it switched to `PHP_EOL`, which will use the system EOL.
