### ISSUE TITLE
Add filter/hook/constant to prevent serving cached content

### ISSUE THREAD

**Issue by Asgaros** [Automattic/wp-super-cache#682]
A filter/hook/constant for third-party plugin-developers would be great which could be used to disable serving cached content programmatically. There might be the necessity for a plugin to disable caching completely for a page where the third-party plugin is running. However, it seems that such a filter/hook/constant is not available for this yet.

I know there is the possibility for users to disable caching based on certain rules manually in the backend, but especially for unexperienced users it could be difficult to do this - or in some case users may even not be aware of the fact that a caching-plugin is causing an issue. To improve the user-experience for those users, it would be great if third-party plugin-developers could programmatically disable serving cached content by using a filter/hook/constant directly.

There is already a `DONOTCACHEPAGE` constant available, however it only prevents caching if the page is not already cached. If the page is already cached, the cached version is still getting served. A similar constant called `DONOTSERVECACHEDPAGE` could solve this issue.

**Comment by donnchawp** [comment]
Done. I added a new constant "WPSC_SERVE_DISABLED" in https://github.com/Automattic/wp-super-cache/commit/d32360b7b2a4bf5413f911a9668359d07fdb263d that you can use to disable serving of cached files.
