### ISSUE TITLE
CDN stopped working with 1.6.8

### ISSUE THREAD

**Issue by esolix** [Automattic/wp-super-cache#696]
Looks like CDN URL is not being served to "logged in users" and on single post output after 1.6.8 update. Reverting to 1.6.7 fixed the issue. Was able to reproduce it on newly installed WP also. https://wordpress.org/support/topic/enable-cdn-support-not-work-if-you-logged-in/

**Comment by donnchawp** [comment]
I could only replicate this if I had changed the "Cache Restrictions" settings. If caching was allowed for all users the CDN works fine. It's disabled if caching is disabled for logged in users or users with a cookie. That's how it's supposed to work unfortunately.

Do you have caching restricted?

**Comment by esolix** [comment]
Thanks, yes we had "Disable caching for logged in visitors. (Recommended)" selected, in the previous version this does not overwrite CDN url replacement string. Has it changed on 1.6.8 forward?

**Comment by donnchawp** [comment]
It has changed but that's an unforeseen bug in how the plugin stopped caching for those users and will have to be fixed.

**Comment by donnchawp** [comment]
If you know how to apply patches the code in https://github.com/Automattic/wp-super-cache/pull/698 should fix the problem. It did for me when I tested it.

**Comment by esolix** [comment]
Thanks! Will test it now

**Comment by esolix** [comment]
> If you know how to apply patches the code in #698 should fix the problem. It did for me when I tested it.

Works great! Thanks!

**Comment by donnchawp** [comment]
Great, I just merged the change so this will go out in the next version.
