### ISSUE TITLE
Undefined index: HTTP_HOST

### ISSUE THREAD

**Issue by kraftbj** [Automattic/wp-super-cache#7]
Notice: Undefined index: HTTP_HOST in /home/kraftbj/public_html/wp-content/plugins/wp-super-cache/wp-cache-base.php on line 13

https://github.com/Automattic/wp-super-cache/blob/master/wp-cache-base.php#L13

**Comment by kraftbj** [comment]
Steps to duplicate: Use WP CLI :)

**Comment by egifford** [comment]
It looks like this issue has a fan club:
https://wordpress.org/support/topic/wp-super-cache-crashes-php-cron-job

I wish I could provide a pull request, but I don't fully understand the code in wp-cache-base.php or what the ramifications are for multisite if I messed it up.

**Comment by bozzmedia** [comment]
Any update on this? I experience the same issue though we're not running WP-CLI. The link to the wp.org forums above is consistent with our error reports. Thanks!

**Comment by jom** [comment]
This should be fixed in https://github.com/Automattic/wp-super-cache/commit/57adc337390d95f05eb8051bc2ef0eafe176cab8 (v1.5.0)
