### ISSUE TITLE
1.4.5 breaks gzip caching due to missing .htaccess rules

### ISSUE THREAD

**Issue by robertmathews** [Automattic/wp-super-cache#70]
There are several reports that version 1.4.5 breaks gzip caching, and I've been able to duplicate this. See (this thread)[https://wordpress.org/support/topic/all-website-pages-downloading-gz-file-after-latest-update].

The bug is in line 1454 of "wp-cache.php":

    if( !is_file( $cache_path . '.htaccess' ) ) {
      $gziprules = insert_with_markers( $cache_path . '.htaccess', 'supercache'...

This says "if the file at /wp-content/cache/.htaccess doesn't exist, create one that contains the gzip rules".

That always worked before version 1.4.5, because nothing else creates that file. But in 1.4.5, the file has already been created by `function wp_cache_add_index_protection()`, so the line 1454 test now fails to add the necessary gzip rules.

I think the `if( !is_file` at line 1454 should probably just be removed completely, making it run insert_with_markers whether the .htaccess file already exists or not.

**Comment by kraftbj** [comment]
Fixed in 15c8adfdf768c618d61858b36cda4ae6ba027990 . SVN trunk updated. Assuming nothing crops up with anyone testing it, 1.4.6 will go out tomorrow.
