### ISSUE TITLE
Store cached pages in memcached

### ISSUE THREAD

**Issue by antonzol** [Automattic/wp-super-cache#706]
Hello!
wp-super-cache is the best cache plugin.
Do U plan to add memcached support to store cached pages in memcached?
I think it's nice feature to speed up website additionally.

**Comment by donnchawp** [comment]
The plugin used to have very rudimentary support for using wp-cache-get/set, or memcached to store cached content but it was very very rough and never worked on. It was removed recently and nobody noticed.

Batcache is a much better choice if you want to use a memcached full page cache.
