### ISSUE TITLE
Ensure preloading in a multi-server environment doesn't cause contention

### ISSUE THREAD

**Issue by atraver** [Automattic/wp-super-cache#707]
I've got WP Super Cache installed in an AWS Elastic Beanstalk environment that has, at any given time, at least 2 servers (and sometimes more). In order to have all of these servers share the same cache, I've configured them to use an NFS mount via AWS Elastic File System.

Furthermore, I've enabled preloading every with a refresh cycle of 720 minutes, since we're trying to ensure our site is heavily cached at all times.

My question is, how can I be sure that, while server 1 is refreshing its preloaded files, server 2 isn't also doing so and effectively overwriting the work server 1 just did? I'm hoping there's some kind of locking mechanism that WP Super Cache utilizes the avoid this issue, but I just wanted to make sure.

**Comment by donnchawp** [comment]
You shouldn't really be using wp-super-cache in a multi-server environment. You would be much better off with something like Batcache that uses memcached to store everything.

NFS isn't a very good choice for holding a cache directory. You could possibly have separate cache directories on each server with one server being the master server and others syncing with that but it would be a huge pain.
