### ISSUE TITLE
WP Super Cache does not clear category and tag pages in some cases

### ISSUE THREAD

**Issue by robertmathews** [Automattic/wp-super-cache#71]
I have a WordPress installation using these settings:

permalink_structure: /posts/%postname%/
category_base: /category/
tag_base: &lt;no value>

WP Super Cache doesn't clear the cached page for a matching tag when I publish a new post with that tag, although it does clear the categories.

I've traced the problem to the "wpsc_delete_cats_tags" function in wp-cache-phase2.php:

```
$tag_base = get_option( 'tag_base' );
if ( $tag_base == '' )
    $tag_base = '/tag/';
```

This isn't right: on my system, the correct path begins with "/posts/tag/". The difference means that `wpsc_delete_cats_tags()` doesn't find and delete the obsolete tag file.

In "wp-includes/rewrite.php", there's documentation for get_tag_permastruct() that says:

```
* If the tag_base property has no value, then the tag structure will have
* the front property value, followed by 'tag', and finally '%tag%'. If it
* does, then the root property will be used, along with the tag_base
* property value.
```

Note that it says it first begins with the "front property value" -- that is, the first part of the posts permalink ("/posts/" in my case). It's not necessarily just "/tag/".

(I think that documentation might be slightly wrong, because when I call get_tag_permastruct, what I get back ends in "%post_tag%", not "%tag%". But that's unrelated to the problem at hand.)

There's similar code for categories:

```
$category_base = get_option( 'category_base');
if ( $category_base == '' )
    $category_base = '/category/';
```

... but I wasn't affected by this because I have category_base set.

Perhaps these could be replaced with code that calls `$wp_rewrite->get_tag_permastruct()` and `$wp_rewrite->get_category_permastruct()`, then does a `str_replace` to remove the trailing "%post_tag%" and "%category%"?

**Comment by Sophist-UK** [comment]
See Automattic/wp-super-cache#98 for a discussion on cache invalidation for posts.

**Comment by Sophist-UK** [comment]
Possible duplication of Automattic/wp-super-cache#966.

**Comment by jom** [comment]
I was able to reproduce with 1.5.8-dev (https://github.com/Automattic/wp-super-cache/commit/3931724d3770e7ce4d1ae141609b8bb0a537c29c).

**Comment by stodorovic** [comment]
I've created function `wpsc_delete_post_archives` which uses get_term_link, get_post_type_archive_link, get_author_posts_url to get proper URLs.
I just found other issue because some actions aren't always added and functions which delete cache aren't fired. I think that PR Automattic/wp-super-cache#506 probably fixes this issue.

**Comment by robertmathews** [comment]
I've verified that this bug was fixed in the solution to PR Automattic/wp-super-cache#387 (which is actually a duplicate of this bug), so I'm marking it closed.
