### ISSUE TITLE
Ignore query string, not bypass cache

### ISSUE THREAD

**Issue by kristos80** [Automattic/wp-super-cache#712]
Hi there,

Thanks for your great plugin first of all.

I found a lot of support tickets, blog comments, etc, regarding a huge issue --in my opinion, that doesn't seem to have been issued with a permanent solution: The ability of the plugin to ignore specific query string parameters.

With huge traffic coming nowadays from social networks and/or 3rd party sources, any caching mechanism should be able to ignore specific query string parameters (such as utm sources) without the need for URL rewriting.

So this is not an issue per se, but rather a request for a feature that is extremely important.

**Comment by astbarc** [comment]
I totally agree with you, this is a very huge problem. Any visit from facebook or google ads is never cached.

Does anyone know any way to implement this? Any workarounds?

**Comment by idoschor** [comment]
@astbarc Overriding `$wp_cache_request_uri` has worked for me. As suggested here: https://wordpress.org/support/topic/ignore-parameters/

**Comment by mahnunchik** [comment]
I think it should be added to documentation. Also interesting how to configure apache to skip `utm_*`, `gclid` etc params.

**Comment by astbarc** [comment]
Thanks for solution @idoschor 

@donnchawp  Would be great for the plugin to have an option to indicate which parameters we want to exclude: utm, gclid, fbclid instead of having to hardcode the plugin.

**Comment by tschoartschi** [comment]
Is it still the best option, to modify the plugin? I guess this could be troublesome when I want to upgrade the plugin 🤔

**Comment by lkraav** [comment]
Correct, https://github.com/Automattic/wp-super-cache/issues/712#issuecomment-547336896 is at best a temporary hack solution.

Plugin should provide filter hooks or configuration options for this. Before Comet Cache died, we were working on defining implementation requirements at https://github.com/wpsharks/comet-cache/issues/850

There's more to consider than meets the eye, incl. always normalizing query param order to determine correct caching status.

But definitely doable, if someone invested time and/or money.

This could potentially be a solid Upwork target.

**Comment by lukapaunovic** [comment]
GCLID, FBCLID, IGSHD....
and many others, this is a huge problem.

**Comment by lynt-smitka** [comment]
@mahnunchik for serverside skip you can try our configs:

Apache (.htaccess): https://gist.github.com/lynt-smitka/297004bed3aa4fb3065af16fd6e7ff18
Nginx (config): https://gist.github.com/lynt-smitka/b8bf0a4b7e2a9e5802faa48ee16b19b0

**Comment by markfinst** [comment]
The option "Don't cache pages with GET parameters." option does not really help, the htaccess modification by @lynt-smitka also doesn't solve the problem with some URLs.


You want to cache pages like `https://example.com/shoes/?filter_brand=nike`, which are pretty common (in WooCommerce fpr example).

If url like this appears `https://example.com/shoes/?filter_brand=nike&gclid=123123123123`, the caching system should just ignore `gclid` part of URL and serve cached version.

Completely redirecting pages with ad-parameters is not an option, since you want JavaScript trackers to see them

Here is an example of code that removes tracking params from a URL:

```php
function remove_tracking_params_from_url($url) {
  $parsedUrl = parse_url($url);
  $query = array();

  if (isset($parsedUrl['query'])) {
    parse_str($parsedUrl['query'], $query);
    $q_params_to_ignore = array(
      'fbclid', 'ref', 'gclid', 'fb_source', 'mc_cid', 'mc_eid',
      'utm_source', 'utm_medium', 'utm_campaign', 'utm_term', 'utm_content', 'utm_expid',
    );
    foreach($q_params_to_ignore as $param_name) {
      unset($query[$param_name]);
    }
  }

  $path = isset($parsedUrl['path']) ? $parsedUrl['path'] : '';
  $query = !empty($query) ? '?'. http_build_query($query) : '';

  return $parsedUrl['scheme']. '://'. $parsedUrl['host']. $path. $query;
}
```

It would be nice if there was a filter, or config file, or something that would allow this without modifying core.

**Comment by lkraav** [comment]
Why not file this as pull request @markfinst might get things moving faster.

**Comment by astbarc** [comment]
Hi @donnchawp,

I've tested it and it also works for me.

Huge thanks for adding this funcionality.
