### ISSUE TITLE
Add filter to change `WP_CACHE` line which gets written to wp-config.php

### ISSUE THREAD

**Issue by JacobDB** [Automattic/wp-super-cache#715]
I need to entirely exclude IE from viewing cached pages. To do this, I can modify `define('WP_CACHE', true)` in my `wp-config.php` to the following:

```php
if (!(stripos($_SERVER["HTTP_USER_AGENT"], "MSIE") || stripos($_SERVER["HTTP_USER_AGENT"], "Trident"))) {
    define('WP_CACHE', true);
}
```

This works perfectly, but I'd like to be able to change this line via a filter in my theme. I see that the line gets defined at `wp-cache.php:2665`. Can we please get a filter on this line so as to facilitate modification?

**Comment by donnchawp** [comment]
You could also use a WP Super Cache plugin that checks the user agent. If it's MSIE then:
define the constant DONOTCACHEPAGE to stop the page being cached.
define the constant WPSC_SERVE_DISABLED to stop a cached page being served.

**Comment by JacobDB** [comment]
Thanks, that's helpful &ndash; what hook should I define this at, `init`?

**Comment by JacobDB** [comment]
Oh interesting, I missed the bit that it *has* to be a plugin. Is there no way to do this as a filter in a theme? Not that big of a deal if not, just would be easier for my use case.

**Comment by JacobDB** [comment]
Alright, I've been tooling around with this this morning but I'm not having much luck getting it to be recognized.

My plugin is extremely simple, all that's in it is:

```php
<?php
if (stripos($_SERVER["HTTP_USER_AGENT"], "MSIE") || stripos($_SERVER["HTTP_USER_AGENT"], "Trident")) {
    define("WPSC_SERVE_DISABLED");
}
```

This is at `/wp-content/plugins/wp-super-cache-plugins/disable-msie.php`. 

According to the documentation, "you can also put plugin files in a wp-super-cache-plugins directory in the same directory where the wp-super-cache directory lives," which I assume to mean the `/wp-content/plugins/` directory, but it doesn't seem to be working. I also tried updating `wp-cache-config.php` to point `$wp_cache_plugins_dir` to this directory specifically, which does remove all the "available plugins" in the settings in the back-end, but still doesn't seem to load my plugin. Mine's not listed in the back-end even, which I don't know if it's supposed to be or not.

The documentation says "from version 1.6.3 of WP Super Cache you can use two functions to add or remove plugins from loading," but is this something I *need* to do, or do plugins within the directory automatically get loaded?

Sorry for the confusion, first time delving in to this!

**Comment by BrookeDot** [comment]
Hi @JacobDB, 

I haven't tested this by looking at the documentation I think you may be missing the actual filter. I think it should be something like this:

```
function exclude_ie_from_cache() {

	if ( ! isset( $_SERVER['HTTP_USER_AGENT'] ) ) {
		return;
	}

	if ( stripos( $_SERVER['HTTP_USER_AGENT'], 'MSIE' ) || stripos( $_SERVER['HTTP_USER_AGENT'], 'Trident' ) ) {
		define( 'DONOTCACHEPAGE' );
		define( 'WPSC_SERVE_DISABLED' );
	}
}

add_cacheaction( 'add_cacheaction', 'exclude_ie_from_cache' );
```

As for where to put the plugin this makes it clear that it shouldn't be in the `wp-super-cache/plugins` folder:
> you should not use the wp-super-cache/plugins/ directory...edit your wp-config.php and set $wp_cache_plugins_dir to another directory where you'll put your plugin.

I think if it's still not working perhaps taking a look at the included plugins will be helpful:
https://github.com/Automattic/wp-super-cache/tree/master/plugins
