### ISSUE TITLE
Mobile support broken for jetpack (minileven) plugin 

### ISSUE THREAD

**Issue by talgalili** [Automattic/wp-super-cache#744]
The jetpack mobile theme minileven is deprecated since version jetpack-8.3.0 with no alternative available.

The way to enable it is by downloading it as a standalone plugin from here:
https://github.com/Automattic/minileven

However, this solution is NOT compatible with wp-super-cache (version 1.7.1).

When having the following enabled: jetpack + minileven + wp-super-cache (with the jetpack plugin mobile support turned on + the option of mobile support marked) - the following happen:
1. I clear the cache
2. browsing to some post from my mobile
3. I see the mobile version of the page
4. I browse to the site from my desktop, I see the desktop version
5. I browse to the same post from my mobile again, but now I see the desktop version
6. when I check the cache folder, I see the version of the post + the "-mobile" version of the cache.

Hence, I conclude that the two versions of the cache exists, but that somehow it doesn't recognize that it should serve the mobile version if a desktop version exists.

When I use jetpack version 7.3.2 (when there was still the jetpack mobile theme in the jetpack plugin) - the mobile theme is cached and served with no issue when using wp-super-cache 1.7.1.

One option is to have a new plugin added (called jetpack-minileven?!) did will work for this new situation.

Could you please assist?

Thanks.

**Comment by donnchawp** [comment]
Unfortunately I can't offer you any help with this, especially as the plugin is deprecated. It's likely that plugin won't get any further updates and may stop working with WordPress itself in time so it would be better to find an alternative, sorry.

**Comment by talgalili** [comment]
Hi @donnapep 
Sorry for nagging, but I wasn't able to find a better solution than minileven.
The plugin (https://github.com/Automattic/minileven) is working just fine (even though it's not being updated).
And wp-super-cache was able to deal with it just fine through jetpack. I don't know how to modify wp-super-cache so it would connect to the right paths with the plugin instead of jetpack.
Could you please reconsider? (since this is blocking me from updating my jetpack, since I cannot move to using the minileven plugin)

Thanks upfront!
