### ISSUE TITLE
Can't get WP Super Cache (or any other caching plugin) to work

### ISSUE THREAD

**Issue by oscarfroberg** [Automattic/wp-super-cache#78]
I had it working on a specific site a few days ago but decided to try out some other different caching plugins as well, and at some point they all stopped working. I am kind of clueless as to where to go from here.

Someone had [a similar problem](https://wordpress.org/support/topic/plugin-wp-super-cache-super-cache-doesnt-work-if-wp-cache-was-used-prior) but that didn't work for me.

I've tried doing the following:

* Uninstalled WP Super Cache (and all other caching plugins)
* Deleted wp-content/cache/, wp-content/advanced-cache.php and wp-content/wp-cache-config.php
* Reinstalled WP Super Cache (which regenerates the above files and folders)

I've also tried various other caching plugins but can't get any of them to work. Error/access logs don't show anything. Simply *nothing happens*. Any idea where the problem might be?

Running Nginx, in case that matters.

**Comment by kraftbj** [comment]
Nginx pulls from cache different from Apache and their .htaccess structure. If all are failing, my first thought is the nginx conf rules were not adjusted to use the cache. https://codex.wordpress.org/Nginx#WP_Super_Cache_Rules

**Comment by oscarfroberg** [comment]
Gee, thanks for closing. Added the Nginx conf but it didn't make a difference, as I already suspected. I didn't need to do anything with the Nginx config when I had it working before. I did however find a log file in wp-content/cache/ which outputs this:

15:26:05 27307 / wp_cache_get_cookies_values: return:
15:26:05 27307 / wp_cache_check_mobile:
15:26:05 27307 / supercache dir: /var/www/example.com/wp-content/cache/supercache/www.example.com/
15:26:05 27307 / No Super Cache file found for current URL: /var/www/example.com/wp-content/cache/supercache/www.example.com/index.html
15:26:05 27307 / wp_cache_get_cookies_values: return:
15:26:05 27307 / In WP Cache Phase 2
15:26:05 27307 / Created mutex lock on semaphore: 176251969
15:26:05 27307 / Setting up WordPress actions
15:26:05 27307 / Created output buffer
15:26:05 27307 / Output buffer callback
15:26:05 27307 / No closing html tag. Not caching.
15:26:05 27307 / wp_cache_maybe_dynamic: returned $buffer
15:26:05 27307 / wp_cache_shutdown_callback: collecting meta data.
15:26:05 27307 / Sending 'Content-Type: text/html; charset="UTF-8"' header.
15:26:05 27307 / Did not write meta file: wp-cache-e487723a4efc1d4d265be476518ae8b2.php ** *0* **

Doesn't really tell me more than I already know. Except, it says "No closing html tag", which there is...

**Comment by kraftbj** [comment]
The GitHub repo isn't meant to be for support and at this point, there isn't a bug, so I closed it. It doesn't mean discussion stops or that it can't be reopened as a bug. Additionally, the piece about it happening with all caching plugins leads me to suspect, at this point, a server-side issue and not a bug with WP Super Cache.

I'd suggest providing your URL and enable WPSC's debug log (to grab fresh ones to make sure we're still looking at the same problem).

For that error, it means that one of the closing tags listed on this line wasn't found: https://github.com/Automattic/wp-super-cache/blob/c04eac26b2f912c8a2e62e8a1367c0b33be9f656/wp-cache-phase2.php#L411
