### ISSUE TITLE
Ignore GET-values

### ISSUE THREAD

**Issue by superDuperCyberTechno** [Automattic/wp-super-cache#789]
Is it possible to ignore GET-values so that pages - with or without - GET-values are cached and treatet equally?

There's the option "Don’t cache pages with GET parameters.", but that is not appropriate. I suspect it simply allows pages with identical GET-values to be served from cache.

Say I have the following page: https://example.com/home

Then, a user requests this page: https://example.com/home?somevar=someval

It appears that WP Super Cache treats the the second page as a completely new page. I want it to serve the first page (cached). I still need the GET-values in the URL.

**Comment by lkraav** [comment]
You might be able to accomplish this if add your known URL params to "tracking parameters" list https://github.com/Automattic/wp-super-cache/pull/777/

**Comment by superDuperCyberTechno** [comment]
Good stuff, exactly what I needed.
