### ISSUE TITLE
Wordpress Zero Spam blocked user message gets cached even though no-cache headers are set

### ISSUE THREAD

**Issue by jjcoffee** [Automattic/wp-super-cache#795]
The plugin [Wordpress Zero Spam](https://wordpress.org/plugins/zero-spam/) outputs a 403 blocked message to users who are flagged as spammers. WP Super Cache seems to cache this message (if the cache is emptied just before the block happens). According to [this](https://github.com/bmarshall511/wordpress-zero-spam/commit/76fcba220c37c498e570ca0fb7e19aa0dbd56365), Wordpress Zero Spam outputs no-cache headers on the page with the "blocked" message, so I would expect that this page would not be cached. Is this an issue you can fix on your end, or is there something Wordpress Zero Spam has to do to make sure this page does not get blocked?

I am running the most recent versions of both plugins.

**Comment by donnchawp** [comment]
Those no-cache headers are for browsers and proxies. Unfortunately this plugin doesn't respect those headers as there are other ways for local code to tell the plugin not to cache the page.

That plugin could define the constant "DONOTCACHEPAGE" when it shows the 403  message. That will stop the page being cached.
