### ISSUE TITLE
as I blow a translation for you

### ISSUE THREAD

**Issue by sergio-moreira-costa** [Automattic/wp-super-cache#91]
Hello my name is Sergio, I'm from Brazil. I did the translation into Portuguese of Brazil, and would be sending to you tarem diponibilizando to the community, I wonder how it might be sending. my email is [email redacted]

**Comment by kraftbj** [comment]
Howdy! We're transitioning all translation work over to https://translate.wordpress.org/projects/wp-plugins/wp-super-cache

Please submit the updated strings there. Once it hits 100%, all pt_br users will automatically get offered the updated translation (versus waiting for us to merge it and release a new version of the plugin, the older way of doing it).

**Comment by sergio-moreira-costa** [comment]
https://drive.google.com/folderview?id=0B_maWYW4zsMwY2FGS1dYLUROaHc&usp=sharing

This Portuguese translation package Brazil already 100% translated

**Comment by kraftbj** [comment]
Importing external files is not something I have the capability to do (the pt_br translator editors on w.org could, but I'm not aware of the process of the top of my head). I'll see if there's an easy way to do that.
